// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: api/proto/analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricType int32

const (
	MetricType_UNKNOWN MetricType = 0
	// 描述统计
	MetricType_COUNT    MetricType = 1
	MetricType_SUM      MetricType = 2
	MetricType_MEAN     MetricType = 3
	MetricType_MEDIAN   MetricType = 4
	MetricType_STD      MetricType = 5
	MetricType_VAR      MetricType = 6
	MetricType_MIN      MetricType = 7
	MetricType_MAX      MetricType = 8
	MetricType_Q25      MetricType = 9
	MetricType_Q50      MetricType = 10
	MetricType_Q75      MetricType = 11
	MetricType_IQR      MetricType = 12
	MetricType_SKEWNESS MetricType = 13
	MetricType_KURTOSIS MetricType = 14
	// 分位数
	MetricType_PERCENTILE MetricType = 15
	// 相关性
	MetricType_CORRELATION MetricType = 16
	// 假设检验
	MetricType_T_TEST     MetricType = 17
	MetricType_CHI_SQUARE MetricType = 18
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "COUNT",
		2:  "SUM",
		3:  "MEAN",
		4:  "MEDIAN",
		5:  "STD",
		6:  "VAR",
		7:  "MIN",
		8:  "MAX",
		9:  "Q25",
		10: "Q50",
		11: "Q75",
		12: "IQR",
		13: "SKEWNESS",
		14: "KURTOSIS",
		15: "PERCENTILE",
		16: "CORRELATION",
		17: "T_TEST",
		18: "CHI_SQUARE",
	}
	MetricType_value = map[string]int32{
		"UNKNOWN":     0,
		"COUNT":       1,
		"SUM":         2,
		"MEAN":        3,
		"MEDIAN":      4,
		"STD":         5,
		"VAR":         6,
		"MIN":         7,
		"MAX":         8,
		"Q25":         9,
		"Q50":         10,
		"Q75":         11,
		"IQR":         12,
		"SKEWNESS":    13,
		"KURTOSIS":    14,
		"PERCENTILE":  15,
		"CORRELATION": 16,
		"T_TEST":      17,
		"CHI_SQUARE":  18,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_analytics_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_api_proto_analytics_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{0}
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *DataFrame             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metrics       []*MetricConfig        `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_api_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsRequest) GetData() *DataFrame {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MetricsRequest) GetMetrics() []*MetricConfig {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MetricType             `protobuf:"varint,1,opt,name=type,proto3,enum=analytics.MetricType" json:"type,omitempty"`
	Column        string                 `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricConfig) Reset() {
	*x = MetricConfig{}
	mi := &file_api_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricConfig) ProtoMessage() {}

func (x *MetricConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricConfig.ProtoReflect.Descriptor instead.
func (*MetricConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricConfig) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_UNKNOWN
}

func (x *MetricConfig) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *MetricConfig) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Results       []*MetricResult        `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_api_proto_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MetricsResponse) GetResults() []*MetricResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *MetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MetricResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Details       map[string]float64     `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	StringValue   string                 `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"` // 用于非数值结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricResult) Reset() {
	*x = MetricResult{}
	mi := &file_api_proto_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResult) ProtoMessage() {}

func (x *MetricResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResult.ProtoReflect.Descriptor instead.
func (*MetricResult) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *MetricResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricResult) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricResult) GetDetails() map[string]float64 {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *MetricResult) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

type TrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *DataFrame             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ValueColumn   string                 `protobuf:"bytes,2,opt,name=value_column,json=valueColumn,proto3" json:"value_column,omitempty"` // 要分析的数值列
	Options       *TrendOptions          `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendRequest) Reset() {
	*x = TrendRequest{}
	mi := &file_api_proto_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendRequest) ProtoMessage() {}

func (x *TrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendRequest.ProtoReflect.Descriptor instead.
func (*TrendRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *TrendRequest) GetData() *DataFrame {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TrendRequest) GetValueColumn() string {
	if x != nil {
		return x.ValueColumn
	}
	return ""
}

func (x *TrendRequest) GetOptions() *TrendOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type TrendOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        int32                  `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`                                    // 季节周期（可选）
	Forecast      bool                   `protobuf:"varint,2,opt,name=forecast,proto3" json:"forecast,omitempty"`                                // 是否预测
	ForecastSteps int32                  `protobuf:"varint,3,opt,name=forecast_steps,json=forecastSteps,proto3" json:"forecast_steps,omitempty"` // 预测步数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendOptions) Reset() {
	*x = TrendOptions{}
	mi := &file_api_proto_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendOptions) ProtoMessage() {}

func (x *TrendOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendOptions.ProtoReflect.Descriptor instead.
func (*TrendOptions) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *TrendOptions) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *TrendOptions) GetForecast() bool {
	if x != nil {
		return x.Forecast
	}
	return false
}

func (x *TrendOptions) GetForecastSteps() int32 {
	if x != nil {
		return x.ForecastSteps
	}
	return 0
}

type TrendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Trend         *TrendResult           `protobuf:"bytes,2,opt,name=trend,proto3" json:"trend,omitempty"`
	Seasonality   *SeasonalityResult     `protobuf:"bytes,3,opt,name=seasonality,proto3" json:"seasonality,omitempty"`
	Forecast      []float64              `protobuf:"fixed64,4,rep,packed,name=forecast,proto3" json:"forecast,omitempty"` // 预测值
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendResponse) Reset() {
	*x = TrendResponse{}
	mi := &file_api_proto_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendResponse) ProtoMessage() {}

func (x *TrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendResponse.ProtoReflect.Descriptor instead.
func (*TrendResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *TrendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrendResponse) GetTrend() *TrendResult {
	if x != nil {
		return x.Trend
	}
	return nil
}

func (x *TrendResponse) GetSeasonality() *SeasonalityResult {
	if x != nil {
		return x.Seasonality
	}
	return nil
}

func (x *TrendResponse) GetForecast() []float64 {
	if x != nil {
		return x.Forecast
	}
	return nil
}

func (x *TrendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TrendResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     string                 `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"` // up, down, flat
	Strength      string                 `protobuf:"bytes,2,opt,name=strength,proto3" json:"strength,omitempty"`   // strong, moderate, weak
	Slope         float64                `protobuf:"fixed64,3,opt,name=slope,proto3" json:"slope,omitempty"`
	RSquared      float64                `protobuf:"fixed64,4,opt,name=r_squared,json=rSquared,proto3" json:"r_squared,omitempty"`
	PValue        float64                `protobuf:"fixed64,5,opt,name=p_value,json=pValue,proto3" json:"p_value,omitempty"`
	CiLower       float64                `protobuf:"fixed64,6,opt,name=ci_lower,json=ciLower,proto3" json:"ci_lower,omitempty"` // 置信区间下限
	CiUpper       float64                `protobuf:"fixed64,7,opt,name=ci_upper,json=ciUpper,proto3" json:"ci_upper,omitempty"` // 置信区间上限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendResult) Reset() {
	*x = TrendResult{}
	mi := &file_api_proto_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendResult) ProtoMessage() {}

func (x *TrendResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendResult.ProtoReflect.Descriptor instead.
func (*TrendResult) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *TrendResult) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *TrendResult) GetStrength() string {
	if x != nil {
		return x.Strength
	}
	return ""
}

func (x *TrendResult) GetSlope() float64 {
	if x != nil {
		return x.Slope
	}
	return 0
}

func (x *TrendResult) GetRSquared() float64 {
	if x != nil {
		return x.RSquared
	}
	return 0
}

func (x *TrendResult) GetPValue() float64 {
	if x != nil {
		return x.PValue
	}
	return 0
}

func (x *TrendResult) GetCiLower() float64 {
	if x != nil {
		return x.CiLower
	}
	return 0
}

func (x *TrendResult) GetCiUpper() float64 {
	if x != nil {
		return x.CiUpper
	}
	return 0
}

type SeasonalityResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HasSeasonality bool                   `protobuf:"varint,1,opt,name=has_seasonality,json=hasSeasonality,proto3" json:"has_seasonality,omitempty"`
	Period         int32                  `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	Strength       float64                `protobuf:"fixed64,3,opt,name=strength,proto3" json:"strength,omitempty"`
	Seasonal       []float64              `protobuf:"fixed64,4,rep,packed,name=seasonal,proto3" json:"seasonal,omitempty"` // 季节性成分
	Trend          []float64              `protobuf:"fixed64,5,rep,packed,name=trend,proto3" json:"trend,omitempty"`       // 趋势成分
	Residual       []float64              `protobuf:"fixed64,6,rep,packed,name=residual,proto3" json:"residual,omitempty"` // 残差
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SeasonalityResult) Reset() {
	*x = SeasonalityResult{}
	mi := &file_api_proto_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeasonalityResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonalityResult) ProtoMessage() {}

func (x *SeasonalityResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonalityResult.ProtoReflect.Descriptor instead.
func (*SeasonalityResult) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *SeasonalityResult) GetHasSeasonality() bool {
	if x != nil {
		return x.HasSeasonality
	}
	return false
}

func (x *SeasonalityResult) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *SeasonalityResult) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *SeasonalityResult) GetSeasonal() []float64 {
	if x != nil {
		return x.Seasonal
	}
	return nil
}

func (x *SeasonalityResult) GetTrend() []float64 {
	if x != nil {
		return x.Trend
	}
	return nil
}

func (x *SeasonalityResult) GetResidual() []float64 {
	if x != nil {
		return x.Residual
	}
	return nil
}

type InsightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *DataFrame             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Options       *InsightOptions        `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsightRequest) Reset() {
	*x = InsightRequest{}
	mi := &file_api_proto_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightRequest) ProtoMessage() {}

func (x *InsightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightRequest.ProtoReflect.Descriptor instead.
func (*InsightRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *InsightRequest) GetData() *DataFrame {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InsightRequest) GetOptions() *InsightOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type InsightOptions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IncludeTrend         bool                   `protobuf:"varint,1,opt,name=include_trend,json=includeTrend,proto3" json:"include_trend,omitempty"`                          // 包含趋势洞察
	IncludeAnomaly       bool                   `protobuf:"varint,2,opt,name=include_anomaly,json=includeAnomaly,proto3" json:"include_anomaly,omitempty"`                    // 包含异常洞察
	IncludeCorrelation   bool                   `protobuf:"varint,3,opt,name=include_correlation,json=includeCorrelation,proto3" json:"include_correlation,omitempty"`        // 包含相关性洞察
	CorrelationThreshold float64                `protobuf:"fixed64,4,opt,name=correlation_threshold,json=correlationThreshold,proto3" json:"correlation_threshold,omitempty"` // 相关性阈值 (默认 0.7)
	AnomalyMethod        string                 `protobuf:"bytes,5,opt,name=anomaly_method,json=anomalyMethod,proto3" json:"anomaly_method,omitempty"`                        // 异常检测方法: iqr, zscore
	AnomalyThreshold     float64                `protobuf:"fixed64,6,opt,name=anomaly_threshold,json=anomalyThreshold,proto3" json:"anomaly_threshold,omitempty"`             // 异常阈值 (默认 3.0 for zscore)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InsightOptions) Reset() {
	*x = InsightOptions{}
	mi := &file_api_proto_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightOptions) ProtoMessage() {}

func (x *InsightOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightOptions.ProtoReflect.Descriptor instead.
func (*InsightOptions) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *InsightOptions) GetIncludeTrend() bool {
	if x != nil {
		return x.IncludeTrend
	}
	return false
}

func (x *InsightOptions) GetIncludeAnomaly() bool {
	if x != nil {
		return x.IncludeAnomaly
	}
	return false
}

func (x *InsightOptions) GetIncludeCorrelation() bool {
	if x != nil {
		return x.IncludeCorrelation
	}
	return false
}

func (x *InsightOptions) GetCorrelationThreshold() float64 {
	if x != nil {
		return x.CorrelationThreshold
	}
	return 0
}

func (x *InsightOptions) GetAnomalyMethod() string {
	if x != nil {
		return x.AnomalyMethod
	}
	return ""
}

func (x *InsightOptions) GetAnomalyThreshold() float64 {
	if x != nil {
		return x.AnomalyThreshold
	}
	return 0
}

type InsightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Insights      []*Insight             `protobuf:"bytes,2,rep,name=insights,proto3" json:"insights,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsightResponse) Reset() {
	*x = InsightResponse{}
	mi := &file_api_proto_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightResponse) ProtoMessage() {}

func (x *InsightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightResponse.ProtoReflect.Descriptor instead.
func (*InsightResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *InsightResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InsightResponse) GetInsights() []*Insight {
	if x != nil {
		return x.Insights
	}
	return nil
}

func (x *InsightResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Insight struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`         // trend_up, trend_down, anomaly_spike, anomaly_dip, correlation
	Severity        string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"` // high, medium, low
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Confidence      float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Evidence        map[string]string      `protobuf:"bytes,6,rep,name=evidence,proto3" json:"evidence,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 证据数据
	Recommendations []string               `protobuf:"bytes,7,rep,name=recommendations,proto3" json:"recommendations,omitempty"`                                                             // 建议
	AffectedMetrics []string               `protobuf:"bytes,8,rep,name=affected_metrics,json=affectedMetrics,proto3" json:"affected_metrics,omitempty"`                                      // 影响的指标
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Insight) Reset() {
	*x = Insight{}
	mi := &file_api_proto_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Insight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Insight) ProtoMessage() {}

func (x *Insight) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Insight.ProtoReflect.Descriptor instead.
func (*Insight) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *Insight) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Insight) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Insight) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Insight) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Insight) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Insight) GetEvidence() map[string]string {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Insight) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *Insight) GetAffectedMetrics() []string {
	if x != nil {
		return x.AffectedMetrics
	}
	return nil
}

type DataFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"` // 列名
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`       // 行数据
	RowCount      int32                  `protobuf:"varint,3,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	ColCount      int32                  `protobuf:"varint,4,opt,name=col_count,json=colCount,proto3" json:"col_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataFrame) Reset() {
	*x = DataFrame{}
	mi := &file_api_proto_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFrame) ProtoMessage() {}

func (x *DataFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFrame.ProtoReflect.Descriptor instead.
func (*DataFrame) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *DataFrame) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *DataFrame) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *DataFrame) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *DataFrame) GetColCount() int32 {
	if x != nil {
		return x.ColCount
	}
	return 0
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"` // 字符串形式存储所有值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_api_proto_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *Row) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_api_proto_analytics_proto protoreflect.FileDescriptor

const file_api_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/analytics.proto\x12\tanalytics\"m\n" +
	"\x0eMetricsRequest\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.analytics.DataFrameR\x04data\x121\n" +
	"\ametrics\x18\x02 \x03(\v2\x17.analytics.MetricConfigR\ametrics\"\xc9\x01\n" +
	"\fMetricConfig\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.analytics.MetricTypeR\x04type\x12\x16\n" +
	"\x06column\x18\x02 \x01(\tR\x06column\x12;\n" +
	"\x06params\x18\x03 \x03(\v2#.analytics.MetricConfig.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x0fMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\aresults\x18\x02 \x03(\v2\x17.analytics.MetricResultR\aresults\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xd7\x01\n" +
	"\fMetricResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12>\n" +
	"\adetails\x18\x03 \x03(\v2$.analytics.MetricResult.DetailsEntryR\adetails\x12!\n" +
	"\fstring_value\x18\x04 \x01(\tR\vstringValue\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x8e\x01\n" +
	"\fTrendRequest\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.analytics.DataFrameR\x04data\x12!\n" +
	"\fvalue_column\x18\x02 \x01(\tR\vvalueColumn\x121\n" +
	"\aoptions\x18\x03 \x01(\v2\x17.analytics.TrendOptionsR\aoptions\"i\n" +
	"\fTrendOptions\x12\x16\n" +
	"\x06period\x18\x01 \x01(\x05R\x06period\x12\x1a\n" +
	"\bforecast\x18\x02 \x01(\bR\bforecast\x12%\n" +
	"\x0eforecast_steps\x18\x03 \x01(\x05R\rforecastSteps\"\xc9\x01\n" +
	"\rTrendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x05trend\x18\x02 \x01(\v2\x16.analytics.TrendResultR\x05trend\x12>\n" +
	"\vseasonality\x18\x03 \x01(\v2\x1c.analytics.SeasonalityResultR\vseasonality\x12\x1a\n" +
	"\bforecast\x18\x04 \x03(\x01R\bforecast\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xc9\x01\n" +
	"\vTrendResult\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\x12\x1a\n" +
	"\bstrength\x18\x02 \x01(\tR\bstrength\x12\x14\n" +
	"\x05slope\x18\x03 \x01(\x01R\x05slope\x12\x1b\n" +
	"\tr_squared\x18\x04 \x01(\x01R\brSquared\x12\x17\n" +
	"\ap_value\x18\x05 \x01(\x01R\x06pValue\x12\x19\n" +
	"\bci_lower\x18\x06 \x01(\x01R\aciLower\x12\x19\n" +
	"\bci_upper\x18\a \x01(\x01R\aciUpper\"\xbe\x01\n" +
	"\x11SeasonalityResult\x12'\n" +
	"\x0fhas_seasonality\x18\x01 \x01(\bR\x0ehasSeasonality\x12\x16\n" +
	"\x06period\x18\x02 \x01(\x05R\x06period\x12\x1a\n" +
	"\bstrength\x18\x03 \x01(\x01R\bstrength\x12\x1a\n" +
	"\bseasonal\x18\x04 \x03(\x01R\bseasonal\x12\x14\n" +
	"\x05trend\x18\x05 \x03(\x01R\x05trend\x12\x1a\n" +
	"\bresidual\x18\x06 \x03(\x01R\bresidual\"o\n" +
	"\x0eInsightRequest\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.analytics.DataFrameR\x04data\x123\n" +
	"\aoptions\x18\x02 \x01(\v2\x19.analytics.InsightOptionsR\aoptions\"\x98\x02\n" +
	"\x0eInsightOptions\x12#\n" +
	"\rinclude_trend\x18\x01 \x01(\bR\fincludeTrend\x12'\n" +
	"\x0finclude_anomaly\x18\x02 \x01(\bR\x0eincludeAnomaly\x12/\n" +
	"\x13include_correlation\x18\x03 \x01(\bR\x12includeCorrelation\x123\n" +
	"\x15correlation_threshold\x18\x04 \x01(\x01R\x14correlationThreshold\x12%\n" +
	"\x0eanomaly_method\x18\x05 \x01(\tR\ranomalyMethod\x12+\n" +
	"\x11anomaly_threshold\x18\x06 \x01(\x01R\x10anomalyThreshold\"q\n" +
	"\x0fInsightResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\binsights\x18\x02 \x03(\v2\x12.analytics.InsightR\binsights\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xe1\x02\n" +
	"\aInsight\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12<\n" +
	"\bevidence\x18\x06 \x03(\v2 .analytics.Insight.EvidenceEntryR\bevidence\x12(\n" +
	"\x0frecommendations\x18\a \x03(\tR\x0frecommendations\x12)\n" +
	"\x10affected_metrics\x18\b \x03(\tR\x0faffectedMetrics\x1a;\n" +
	"\rEvidenceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\tDataFrame\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12\"\n" +
	"\x04rows\x18\x02 \x03(\v2\x0e.analytics.RowR\x04rows\x12\x1b\n" +
	"\trow_count\x18\x03 \x01(\x05R\browCount\x12\x1b\n" +
	"\tcol_count\x18\x04 \x01(\x05R\bcolCount\"\x1d\n" +
	"\x03Row\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values*\xe4\x01\n" +
	"\n" +
	"MetricType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05COUNT\x10\x01\x12\a\n" +
	"\x03SUM\x10\x02\x12\b\n" +
	"\x04MEAN\x10\x03\x12\n" +
	"\n" +
	"\x06MEDIAN\x10\x04\x12\a\n" +
	"\x03STD\x10\x05\x12\a\n" +
	"\x03VAR\x10\x06\x12\a\n" +
	"\x03MIN\x10\a\x12\a\n" +
	"\x03MAX\x10\b\x12\a\n" +
	"\x03Q25\x10\t\x12\a\n" +
	"\x03Q50\x10\n" +
	"\x12\a\n" +
	"\x03Q75\x10\v\x12\a\n" +
	"\x03IQR\x10\f\x12\f\n" +
	"\bSKEWNESS\x10\r\x12\f\n" +
	"\bKURTOSIS\x10\x0e\x12\x0e\n" +
	"\n" +
	"PERCENTILE\x10\x0f\x12\x0f\n" +
	"\vCORRELATION\x10\x10\x12\n" +
	"\n" +
	"\x06T_TEST\x10\x11\x12\x0e\n" +
	"\n" +
	"CHI_SQUARE\x10\x122\xe9\x01\n" +
	"\x10AnalyticsService\x12G\n" +
	"\x0eComputeMetrics\x12\x19.analytics.MetricsRequest\x1a\x1a.analytics.MetricsResponse\x12A\n" +
	"\fAnalyzeTrend\x12\x17.analytics.TrendRequest\x1a\x18.analytics.TrendResponse\x12I\n" +
	"\x10DiscoverInsights\x12\x19.analytics.InsightRequest\x1a\x1a.analytics.InsightResponseB\x1aZ\x18link/api/proto;analyticsb\x06proto3"

var (
	file_api_proto_analytics_proto_rawDescOnce sync.Once
	file_api_proto_analytics_proto_rawDescData []byte
)

func file_api_proto_analytics_proto_rawDescGZIP() []byte {
	file_api_proto_analytics_proto_rawDescOnce.Do(func() {
		file_api_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_analytics_proto_rawDesc), len(file_api_proto_analytics_proto_rawDesc)))
	})
	return file_api_proto_analytics_proto_rawDescData
}

var file_api_proto_analytics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_analytics_proto_goTypes = []any{
	(MetricType)(0),           // 0: analytics.MetricType
	(*MetricsRequest)(nil),    // 1: analytics.MetricsRequest
	(*MetricConfig)(nil),      // 2: analytics.MetricConfig
	(*MetricsResponse)(nil),   // 3: analytics.MetricsResponse
	(*MetricResult)(nil),      // 4: analytics.MetricResult
	(*TrendRequest)(nil),      // 5: analytics.TrendRequest
	(*TrendOptions)(nil),      // 6: analytics.TrendOptions
	(*TrendResponse)(nil),     // 7: analytics.TrendResponse
	(*TrendResult)(nil),       // 8: analytics.TrendResult
	(*SeasonalityResult)(nil), // 9: analytics.SeasonalityResult
	(*InsightRequest)(nil),    // 10: analytics.InsightRequest
	(*InsightOptions)(nil),    // 11: analytics.InsightOptions
	(*InsightResponse)(nil),   // 12: analytics.InsightResponse
	(*Insight)(nil),           // 13: analytics.Insight
	(*DataFrame)(nil),         // 14: analytics.DataFrame
	(*Row)(nil),               // 15: analytics.Row
	nil,                       // 16: analytics.MetricConfig.ParamsEntry
	nil,                       // 17: analytics.MetricResult.DetailsEntry
	nil,                       // 18: analytics.Insight.EvidenceEntry
}
var file_api_proto_analytics_proto_depIdxs = []int32{
	14, // 0: analytics.MetricsRequest.data:type_name -> analytics.DataFrame
	2,  // 1: analytics.MetricsRequest.metrics:type_name -> analytics.MetricConfig
	0,  // 2: analytics.MetricConfig.type:type_name -> analytics.MetricType
	16, // 3: analytics.MetricConfig.params:type_name -> analytics.MetricConfig.ParamsEntry
	4,  // 4: analytics.MetricsResponse.results:type_name -> analytics.MetricResult
	17, // 5: analytics.MetricResult.details:type_name -> analytics.MetricResult.DetailsEntry
	14, // 6: analytics.TrendRequest.data:type_name -> analytics.DataFrame
	6,  // 7: analytics.TrendRequest.options:type_name -> analytics.TrendOptions
	8,  // 8: analytics.TrendResponse.trend:type_name -> analytics.TrendResult
	9,  // 9: analytics.TrendResponse.seasonality:type_name -> analytics.SeasonalityResult
	14, // 10: analytics.InsightRequest.data:type_name -> analytics.DataFrame
	11, // 11: analytics.InsightRequest.options:type_name -> analytics.InsightOptions
	13, // 12: analytics.InsightResponse.insights:type_name -> analytics.Insight
	18, // 13: analytics.Insight.evidence:type_name -> analytics.Insight.EvidenceEntry
	15, // 14: analytics.DataFrame.rows:type_name -> analytics.Row
	1,  // 15: analytics.AnalyticsService.ComputeMetrics:input_type -> analytics.MetricsRequest
	5,  // 16: analytics.AnalyticsService.AnalyzeTrend:input_type -> analytics.TrendRequest
	10, // 17: analytics.AnalyticsService.DiscoverInsights:input_type -> analytics.InsightRequest
	3,  // 18: analytics.AnalyticsService.ComputeMetrics:output_type -> analytics.MetricsResponse
	7,  // 19: analytics.AnalyticsService.AnalyzeTrend:output_type -> analytics.TrendResponse
	12, // 20: analytics.AnalyticsService.DiscoverInsights:output_type -> analytics.InsightResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_proto_analytics_proto_init() }
func file_api_proto_analytics_proto_init() {
	if File_api_proto_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_analytics_proto_rawDesc), len(file_api_proto_analytics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_analytics_proto_goTypes,
		DependencyIndexes: file_api_proto_analytics_proto_depIdxs,
		EnumInfos:         file_api_proto_analytics_proto_enumTypes,
		MessageInfos:      file_api_proto_analytics_proto_msgTypes,
	}.Build()
	File_api_proto_analytics_proto = out.File
	file_api_proto_analytics_proto_goTypes = nil
	file_api_proto_analytics_proto_depIdxs = nil
}
