// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 跨服务统一错误码（架构加固 Phase 4，任务 4.2）。
//
// 单一源：各服务（analytics/docreader/evaluation/judge/quality）的错误语义以此枚举为准，
// 替代散在各 proto 的 string code 字段。当前为契约先行——新增字段/新服务应直接引用
// common.ErrorCode；存量 string code 的迁移作为后续增量，不在本阶段一次性重写以控回归面。
type ErrorCode int32

const (
	// 未指定（proto3 零值，保留位）。
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// 通用类（0–99 段）
	ErrorCode_ERROR_CODE_OK                 ErrorCode = 1 // 成功
	ErrorCode_ERROR_CODE_INTERNAL           ErrorCode = 2 // 服务内部错误
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT   ErrorCode = 3 // 参数非法
	ErrorCode_ERROR_CODE_NOT_FOUND          ErrorCode = 4 // 资源不存在
	ErrorCode_ERROR_CODE_UNAUTHENTICATED    ErrorCode = 5 // 未认证
	ErrorCode_ERROR_CODE_PERMISSION_DENIED  ErrorCode = 6 // 无权限
	ErrorCode_ERROR_CODE_DEADLINE_EXCEEDED  ErrorCode = 7 // 超时
	ErrorCode_ERROR_CODE_UNAVAILABLE        ErrorCode = 8 // 依赖不可用（下游服务/存储）
	ErrorCode_ERROR_CODE_RESOURCE_EXHAUSTED ErrorCode = 9 // 资源耗尽（限流/配额）
	// 领域类（100+ 段，按需扩展）
	ErrorCode_ERROR_CODE_DATASET_NOT_FOUND ErrorCode = 100 // 数据集不存在（evaluation）
	ErrorCode_ERROR_CODE_MODEL_UNAVAILABLE ErrorCode = 101 // 模型不可用（evaluation/judge）
	ErrorCode_ERROR_CODE_COMPUTE_FAILED    ErrorCode = 102 // 指标计算失败（evaluation compute）
	ErrorCode_ERROR_CODE_UPSTREAM_TIMEOUT  ErrorCode = 103 // 上游数据源超时（analytics/docreader）
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "ERROR_CODE_UNSPECIFIED",
		1:   "ERROR_CODE_OK",
		2:   "ERROR_CODE_INTERNAL",
		3:   "ERROR_CODE_INVALID_ARGUMENT",
		4:   "ERROR_CODE_NOT_FOUND",
		5:   "ERROR_CODE_UNAUTHENTICATED",
		6:   "ERROR_CODE_PERMISSION_DENIED",
		7:   "ERROR_CODE_DEADLINE_EXCEEDED",
		8:   "ERROR_CODE_UNAVAILABLE",
		9:   "ERROR_CODE_RESOURCE_EXHAUSTED",
		100: "ERROR_CODE_DATASET_NOT_FOUND",
		101: "ERROR_CODE_MODEL_UNAVAILABLE",
		102: "ERROR_CODE_COMPUTE_FAILED",
		103: "ERROR_CODE_UPSTREAM_TIMEOUT",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":        0,
		"ERROR_CODE_OK":                 1,
		"ERROR_CODE_INTERNAL":           2,
		"ERROR_CODE_INVALID_ARGUMENT":   3,
		"ERROR_CODE_NOT_FOUND":          4,
		"ERROR_CODE_UNAUTHENTICATED":    5,
		"ERROR_CODE_PERMISSION_DENIED":  6,
		"ERROR_CODE_DEADLINE_EXCEEDED":  7,
		"ERROR_CODE_UNAVAILABLE":        8,
		"ERROR_CODE_RESOURCE_EXHAUSTED": 9,
		"ERROR_CODE_DATASET_NOT_FOUND":  100,
		"ERROR_CODE_MODEL_UNAVAILABLE":  101,
		"ERROR_CODE_COMPUTE_FAILED":     102,
		"ERROR_CODE_UPSTREAM_TIMEOUT":   103,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x12\x06common*\xb5\x03\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rERROR_CODE_OK\x10\x01\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x02\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x04\x12\x1e\n" +
	"\x1aERROR_CODE_UNAUTHENTICATED\x10\x05\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\x06\x12 \n" +
	"\x1cERROR_CODE_DEADLINE_EXCEEDED\x10\a\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\b\x12!\n" +
	"\x1dERROR_CODE_RESOURCE_EXHAUSTED\x10\t\x12 \n" +
	"\x1cERROR_CODE_DATASET_NOT_FOUND\x10d\x12 \n" +
	"\x1cERROR_CODE_MODEL_UNAVAILABLE\x10e\x12\x1d\n" +
	"\x19ERROR_CODE_COMPUTE_FAILED\x10f\x12\x1f\n" +
	"\x1bERROR_CODE_UPSTREAM_TIMEOUT\x10gB\x17Z\x15link/api/proto/commonb\x06proto3"

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData []byte
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)))
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_common_proto_goTypes = []any{
	(ErrorCode)(0), // 0: common.ErrorCode
}
var file_proto_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		EnumInfos:         file_proto_common_proto_enumTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
