// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: api/proto/quality.proto

package quality

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QualityService_EvaluateQuality_FullMethodName             = "/quality.QualityService/EvaluateQuality"
	QualityService_EvaluateUnstructuredQuality_FullMethodName = "/quality.QualityService/EvaluateUnstructuredQuality"
	QualityService_CleanData_FullMethodName                   = "/quality.QualityService/CleanData"
	QualityService_ProcessPipeline_FullMethodName             = "/quality.QualityService/ProcessPipeline"
	QualityService_DetectDrift_FullMethodName                 = "/quality.QualityService/DetectDrift"
	QualityService_ListDimensions_FullMethodName              = "/quality.QualityService/ListDimensions"
	QualityService_GetQualityRules_FullMethodName             = "/quality.QualityService/GetQualityRules"
	QualityService_UpdateQualityRules_FullMethodName          = "/quality.QualityService/UpdateQualityRules"
	QualityService_RegisterCustomEvaluator_FullMethodName     = "/quality.QualityService/RegisterCustomEvaluator"
	QualityService_RegisterCustomCleaner_FullMethodName       = "/quality.QualityService/RegisterCustomCleaner"
)

// QualityServiceClient is the client API for QualityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 质量服务
type QualityServiceClient interface {
	// 评估结构化数据质量
	EvaluateQuality(ctx context.Context, in *EvaluateQualityRequest, opts ...grpc.CallOption) (*EvaluateQualityResponse, error)
	// 评估非结构化数据质量
	EvaluateUnstructuredQuality(ctx context.Context, in *EvaluateUnstructuredQualityRequest, opts ...grpc.CallOption) (*EvaluateUnstructuredQualityResponse, error)
	// 清洗数据
	CleanData(ctx context.Context, in *CleanDataRequest, opts ...grpc.CallOption) (*CleanDataResponse, error)
	// 执行端到端流程
	ProcessPipeline(ctx context.Context, in *ProcessPipelineRequest, opts ...grpc.CallOption) (*ProcessPipelineResponse, error)
	// 检测数据漂移
	DetectDrift(ctx context.Context, in *DetectDriftRequest, opts ...grpc.CallOption) (*DetectDriftResponse, error)
	// 列出可用的评估维度
	ListDimensions(ctx context.Context, in *ListDimensionsRequest, opts ...grpc.CallOption) (*ListDimensionsResponse, error)
	// 获取质量规则
	GetQualityRules(ctx context.Context, in *GetQualityRulesRequest, opts ...grpc.CallOption) (*GetQualityRulesResponse, error)
	// 更新质量规则
	UpdateQualityRules(ctx context.Context, in *UpdateQualityRulesRequest, opts ...grpc.CallOption) (*UpdateQualityRulesResponse, error)
	// 注册自定义评估器
	RegisterCustomEvaluator(ctx context.Context, in *RegisterCustomEvaluatorRequest, opts ...grpc.CallOption) (*RegisterCustomEvaluatorResponse, error)
	// 注册自定义清洗器
	RegisterCustomCleaner(ctx context.Context, in *RegisterCustomCleanerRequest, opts ...grpc.CallOption) (*RegisterCustomCleanerResponse, error)
}

type qualityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQualityServiceClient(cc grpc.ClientConnInterface) QualityServiceClient {
	return &qualityServiceClient{cc}
}

func (c *qualityServiceClient) EvaluateQuality(ctx context.Context, in *EvaluateQualityRequest, opts ...grpc.CallOption) (*EvaluateQualityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateQualityResponse)
	err := c.cc.Invoke(ctx, QualityService_EvaluateQuality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityServiceClient) EvaluateUnstructuredQuality(ctx context.Context, in *EvaluateUnstructuredQualityRequest, opts ...grpc.CallOption) (*EvaluateUnstructuredQualityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateUnstructuredQualityResponse)
	err := c.cc.Invoke(ctx, QualityService_EvaluateUnstructuredQuality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityServiceClient) CleanData(ctx context.Context, in *CleanDataRequest, opts ...grpc.CallOption) (*CleanDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanDataResponse)
	err := c.cc.Invoke(ctx, QualityService_CleanData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityServiceClient) ProcessPipeline(ctx context.Context, in *ProcessPipelineRequest, opts ...grpc.CallOption) (*ProcessPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessPipelineResponse)
	err := c.cc.Invoke(ctx, QualityService_ProcessPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityServiceClient) DetectDrift(ctx context.Context, in *DetectDriftRequest, opts ...grpc.CallOption) (*DetectDriftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectDriftResponse)
	err := c.cc.Invoke(ctx, QualityService_DetectDrift_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityServiceClient) ListDimensions(ctx context.Context, in *ListDimensionsRequest, opts ...grpc.CallOption) (*ListDimensionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDimensionsResponse)
	err := c.cc.Invoke(ctx, QualityService_ListDimensions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityServiceClient) GetQualityRules(ctx context.Context, in *GetQualityRulesRequest, opts ...grpc.CallOption) (*GetQualityRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQualityRulesResponse)
	err := c.cc.Invoke(ctx, QualityService_GetQualityRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityServiceClient) UpdateQualityRules(ctx context.Context, in *UpdateQualityRulesRequest, opts ...grpc.CallOption) (*UpdateQualityRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateQualityRulesResponse)
	err := c.cc.Invoke(ctx, QualityService_UpdateQualityRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityServiceClient) RegisterCustomEvaluator(ctx context.Context, in *RegisterCustomEvaluatorRequest, opts ...grpc.CallOption) (*RegisterCustomEvaluatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterCustomEvaluatorResponse)
	err := c.cc.Invoke(ctx, QualityService_RegisterCustomEvaluator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityServiceClient) RegisterCustomCleaner(ctx context.Context, in *RegisterCustomCleanerRequest, opts ...grpc.CallOption) (*RegisterCustomCleanerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterCustomCleanerResponse)
	err := c.cc.Invoke(ctx, QualityService_RegisterCustomCleaner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QualityServiceServer is the server API for QualityService service.
// All implementations must embed UnimplementedQualityServiceServer
// for forward compatibility.
//
// 质量服务
type QualityServiceServer interface {
	// 评估结构化数据质量
	EvaluateQuality(context.Context, *EvaluateQualityRequest) (*EvaluateQualityResponse, error)
	// 评估非结构化数据质量
	EvaluateUnstructuredQuality(context.Context, *EvaluateUnstructuredQualityRequest) (*EvaluateUnstructuredQualityResponse, error)
	// 清洗数据
	CleanData(context.Context, *CleanDataRequest) (*CleanDataResponse, error)
	// 执行端到端流程
	ProcessPipeline(context.Context, *ProcessPipelineRequest) (*ProcessPipelineResponse, error)
	// 检测数据漂移
	DetectDrift(context.Context, *DetectDriftRequest) (*DetectDriftResponse, error)
	// 列出可用的评估维度
	ListDimensions(context.Context, *ListDimensionsRequest) (*ListDimensionsResponse, error)
	// 获取质量规则
	GetQualityRules(context.Context, *GetQualityRulesRequest) (*GetQualityRulesResponse, error)
	// 更新质量规则
	UpdateQualityRules(context.Context, *UpdateQualityRulesRequest) (*UpdateQualityRulesResponse, error)
	// 注册自定义评估器
	RegisterCustomEvaluator(context.Context, *RegisterCustomEvaluatorRequest) (*RegisterCustomEvaluatorResponse, error)
	// 注册自定义清洗器
	RegisterCustomCleaner(context.Context, *RegisterCustomCleanerRequest) (*RegisterCustomCleanerResponse, error)
	mustEmbedUnimplementedQualityServiceServer()
}

// UnimplementedQualityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQualityServiceServer struct{}

func (UnimplementedQualityServiceServer) EvaluateQuality(context.Context, *EvaluateQualityRequest) (*EvaluateQualityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateQuality not implemented")
}
func (UnimplementedQualityServiceServer) EvaluateUnstructuredQuality(context.Context, *EvaluateUnstructuredQualityRequest) (*EvaluateUnstructuredQualityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateUnstructuredQuality not implemented")
}
func (UnimplementedQualityServiceServer) CleanData(context.Context, *CleanDataRequest) (*CleanDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanData not implemented")
}
func (UnimplementedQualityServiceServer) ProcessPipeline(context.Context, *ProcessPipelineRequest) (*ProcessPipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessPipeline not implemented")
}
func (UnimplementedQualityServiceServer) DetectDrift(context.Context, *DetectDriftRequest) (*DetectDriftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectDrift not implemented")
}
func (UnimplementedQualityServiceServer) ListDimensions(context.Context, *ListDimensionsRequest) (*ListDimensionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDimensions not implemented")
}
func (UnimplementedQualityServiceServer) GetQualityRules(context.Context, *GetQualityRulesRequest) (*GetQualityRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQualityRules not implemented")
}
func (UnimplementedQualityServiceServer) UpdateQualityRules(context.Context, *UpdateQualityRulesRequest) (*UpdateQualityRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateQualityRules not implemented")
}
func (UnimplementedQualityServiceServer) RegisterCustomEvaluator(context.Context, *RegisterCustomEvaluatorRequest) (*RegisterCustomEvaluatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCustomEvaluator not implemented")
}
func (UnimplementedQualityServiceServer) RegisterCustomCleaner(context.Context, *RegisterCustomCleanerRequest) (*RegisterCustomCleanerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCustomCleaner not implemented")
}
func (UnimplementedQualityServiceServer) mustEmbedUnimplementedQualityServiceServer() {}
func (UnimplementedQualityServiceServer) testEmbeddedByValue()                        {}

// UnsafeQualityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QualityServiceServer will
// result in compilation errors.
type UnsafeQualityServiceServer interface {
	mustEmbedUnimplementedQualityServiceServer()
}

func RegisterQualityServiceServer(s grpc.ServiceRegistrar, srv QualityServiceServer) {
	// If the following call panics, it indicates UnimplementedQualityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QualityService_ServiceDesc, srv)
}

func _QualityService_EvaluateQuality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateQualityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityServiceServer).EvaluateQuality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityService_EvaluateQuality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityServiceServer).EvaluateQuality(ctx, req.(*EvaluateQualityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityService_EvaluateUnstructuredQuality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateUnstructuredQualityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityServiceServer).EvaluateUnstructuredQuality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityService_EvaluateUnstructuredQuality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityServiceServer).EvaluateUnstructuredQuality(ctx, req.(*EvaluateUnstructuredQualityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityService_CleanData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityServiceServer).CleanData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityService_CleanData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityServiceServer).CleanData(ctx, req.(*CleanDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityService_ProcessPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityServiceServer).ProcessPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityService_ProcessPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityServiceServer).ProcessPipeline(ctx, req.(*ProcessPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityService_DetectDrift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectDriftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityServiceServer).DetectDrift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityService_DetectDrift_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityServiceServer).DetectDrift(ctx, req.(*DetectDriftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityService_ListDimensions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDimensionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityServiceServer).ListDimensions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityService_ListDimensions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityServiceServer).ListDimensions(ctx, req.(*ListDimensionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityService_GetQualityRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQualityRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityServiceServer).GetQualityRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityService_GetQualityRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityServiceServer).GetQualityRules(ctx, req.(*GetQualityRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityService_UpdateQualityRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQualityRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityServiceServer).UpdateQualityRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityService_UpdateQualityRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityServiceServer).UpdateQualityRules(ctx, req.(*UpdateQualityRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityService_RegisterCustomEvaluator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCustomEvaluatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityServiceServer).RegisterCustomEvaluator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityService_RegisterCustomEvaluator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityServiceServer).RegisterCustomEvaluator(ctx, req.(*RegisterCustomEvaluatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityService_RegisterCustomCleaner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCustomCleanerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityServiceServer).RegisterCustomCleaner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityService_RegisterCustomCleaner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityServiceServer).RegisterCustomCleaner(ctx, req.(*RegisterCustomCleanerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QualityService_ServiceDesc is the grpc.ServiceDesc for QualityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QualityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quality.QualityService",
	HandlerType: (*QualityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateQuality",
			Handler:    _QualityService_EvaluateQuality_Handler,
		},
		{
			MethodName: "EvaluateUnstructuredQuality",
			Handler:    _QualityService_EvaluateUnstructuredQuality_Handler,
		},
		{
			MethodName: "CleanData",
			Handler:    _QualityService_CleanData_Handler,
		},
		{
			MethodName: "ProcessPipeline",
			Handler:    _QualityService_ProcessPipeline_Handler,
		},
		{
			MethodName: "DetectDrift",
			Handler:    _QualityService_DetectDrift_Handler,
		},
		{
			MethodName: "ListDimensions",
			Handler:    _QualityService_ListDimensions_Handler,
		},
		{
			MethodName: "GetQualityRules",
			Handler:    _QualityService_GetQualityRules_Handler,
		},
		{
			MethodName: "UpdateQualityRules",
			Handler:    _QualityService_UpdateQualityRules_Handler,
		},
		{
			MethodName: "RegisterCustomEvaluator",
			Handler:    _QualityService_RegisterCustomEvaluator_Handler,
		},
		{
			MethodName: "RegisterCustomCleaner",
			Handler:    _QualityService_RegisterCustomCleaner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/quality.proto",
}
