// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: api/proto/docreader.proto

package docreader

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentReaderService_ParseDocument_FullMethodName = "/docreader.DocumentReaderService/ParseDocument"
	DocumentReaderService_ParseBatch_FullMethodName    = "/docreader.DocumentReaderService/ParseBatch"
	DocumentReaderService_OCRImage_FullMethodName      = "/docreader.DocumentReaderService/OCRImage"
	DocumentReaderService_OCRBatch_FullMethodName      = "/docreader.DocumentReaderService/OCRBatch"
	DocumentReaderService_ChunkDocument_FullMethodName = "/docreader.DocumentReaderService/ChunkDocument"
	DocumentReaderService_FetchURL_FullMethodName      = "/docreader.DocumentReaderService/FetchURL"
)

// DocumentReaderServiceClient is the client API for DocumentReaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 文档解析服务
type DocumentReaderServiceClient interface {
	// ===== 文档解析 =====
	ParseDocument(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error)
	ParseBatch(ctx context.Context, in *ParseBatchRequest, opts ...grpc.CallOption) (*ParseBatchResponse, error)
	// ===== OCR 识别 =====
	OCRImage(ctx context.Context, in *OCRRequest, opts ...grpc.CallOption) (*OCRResponse, error)
	OCRBatch(ctx context.Context, in *OCRBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OCRBatchResponse], error)
	// ===== 文档分块 =====
	ChunkDocument(ctx context.Context, in *ChunkRequest, opts ...grpc.CallOption) (*ChunkResponse, error)
	// ===== URL 内容获取 =====
	FetchURL(ctx context.Context, in *FetchURLRequest, opts ...grpc.CallOption) (*FetchURLResponse, error)
}

type documentReaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentReaderServiceClient(cc grpc.ClientConnInterface) DocumentReaderServiceClient {
	return &documentReaderServiceClient{cc}
}

func (c *documentReaderServiceClient) ParseDocument(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseResponse)
	err := c.cc.Invoke(ctx, DocumentReaderService_ParseDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentReaderServiceClient) ParseBatch(ctx context.Context, in *ParseBatchRequest, opts ...grpc.CallOption) (*ParseBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseBatchResponse)
	err := c.cc.Invoke(ctx, DocumentReaderService_ParseBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentReaderServiceClient) OCRImage(ctx context.Context, in *OCRRequest, opts ...grpc.CallOption) (*OCRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OCRResponse)
	err := c.cc.Invoke(ctx, DocumentReaderService_OCRImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentReaderServiceClient) OCRBatch(ctx context.Context, in *OCRBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OCRBatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocumentReaderService_ServiceDesc.Streams[0], DocumentReaderService_OCRBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OCRBatchRequest, OCRBatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentReaderService_OCRBatchClient = grpc.ServerStreamingClient[OCRBatchResponse]

func (c *documentReaderServiceClient) ChunkDocument(ctx context.Context, in *ChunkRequest, opts ...grpc.CallOption) (*ChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkResponse)
	err := c.cc.Invoke(ctx, DocumentReaderService_ChunkDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentReaderServiceClient) FetchURL(ctx context.Context, in *FetchURLRequest, opts ...grpc.CallOption) (*FetchURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchURLResponse)
	err := c.cc.Invoke(ctx, DocumentReaderService_FetchURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentReaderServiceServer is the server API for DocumentReaderService service.
// All implementations must embed UnimplementedDocumentReaderServiceServer
// for forward compatibility.
//
// 文档解析服务
type DocumentReaderServiceServer interface {
	// ===== 文档解析 =====
	ParseDocument(context.Context, *ParseRequest) (*ParseResponse, error)
	ParseBatch(context.Context, *ParseBatchRequest) (*ParseBatchResponse, error)
	// ===== OCR 识别 =====
	OCRImage(context.Context, *OCRRequest) (*OCRResponse, error)
	OCRBatch(*OCRBatchRequest, grpc.ServerStreamingServer[OCRBatchResponse]) error
	// ===== 文档分块 =====
	ChunkDocument(context.Context, *ChunkRequest) (*ChunkResponse, error)
	// ===== URL 内容获取 =====
	FetchURL(context.Context, *FetchURLRequest) (*FetchURLResponse, error)
	mustEmbedUnimplementedDocumentReaderServiceServer()
}

// UnimplementedDocumentReaderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentReaderServiceServer struct{}

func (UnimplementedDocumentReaderServiceServer) ParseDocument(context.Context, *ParseRequest) (*ParseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseDocument not implemented")
}
func (UnimplementedDocumentReaderServiceServer) ParseBatch(context.Context, *ParseBatchRequest) (*ParseBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseBatch not implemented")
}
func (UnimplementedDocumentReaderServiceServer) OCRImage(context.Context, *OCRRequest) (*OCRResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OCRImage not implemented")
}
func (UnimplementedDocumentReaderServiceServer) OCRBatch(*OCRBatchRequest, grpc.ServerStreamingServer[OCRBatchResponse]) error {
	return status.Error(codes.Unimplemented, "method OCRBatch not implemented")
}
func (UnimplementedDocumentReaderServiceServer) ChunkDocument(context.Context, *ChunkRequest) (*ChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChunkDocument not implemented")
}
func (UnimplementedDocumentReaderServiceServer) FetchURL(context.Context, *FetchURLRequest) (*FetchURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchURL not implemented")
}
func (UnimplementedDocumentReaderServiceServer) mustEmbedUnimplementedDocumentReaderServiceServer() {}
func (UnimplementedDocumentReaderServiceServer) testEmbeddedByValue()                               {}

// UnsafeDocumentReaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentReaderServiceServer will
// result in compilation errors.
type UnsafeDocumentReaderServiceServer interface {
	mustEmbedUnimplementedDocumentReaderServiceServer()
}

func RegisterDocumentReaderServiceServer(s grpc.ServiceRegistrar, srv DocumentReaderServiceServer) {
	// If the following call panics, it indicates UnimplementedDocumentReaderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentReaderService_ServiceDesc, srv)
}

func _DocumentReaderService_ParseDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentReaderServiceServer).ParseDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentReaderService_ParseDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentReaderServiceServer).ParseDocument(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentReaderService_ParseBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentReaderServiceServer).ParseBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentReaderService_ParseBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentReaderServiceServer).ParseBatch(ctx, req.(*ParseBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentReaderService_OCRImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OCRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentReaderServiceServer).OCRImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentReaderService_OCRImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentReaderServiceServer).OCRImage(ctx, req.(*OCRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentReaderService_OCRBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OCRBatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocumentReaderServiceServer).OCRBatch(m, &grpc.GenericServerStream[OCRBatchRequest, OCRBatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocumentReaderService_OCRBatchServer = grpc.ServerStreamingServer[OCRBatchResponse]

func _DocumentReaderService_ChunkDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentReaderServiceServer).ChunkDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentReaderService_ChunkDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentReaderServiceServer).ChunkDocument(ctx, req.(*ChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentReaderService_FetchURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentReaderServiceServer).FetchURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentReaderService_FetchURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentReaderServiceServer).FetchURL(ctx, req.(*FetchURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentReaderService_ServiceDesc is the grpc.ServiceDesc for DocumentReaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentReaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docreader.DocumentReaderService",
	HandlerType: (*DocumentReaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseDocument",
			Handler:    _DocumentReaderService_ParseDocument_Handler,
		},
		{
			MethodName: "ParseBatch",
			Handler:    _DocumentReaderService_ParseBatch_Handler,
		},
		{
			MethodName: "OCRImage",
			Handler:    _DocumentReaderService_OCRImage_Handler,
		},
		{
			MethodName: "ChunkDocument",
			Handler:    _DocumentReaderService_ChunkDocument_Handler,
		},
		{
			MethodName: "FetchURL",
			Handler:    _DocumentReaderService_FetchURL_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OCRBatch",
			Handler:       _DocumentReaderService_OCRBatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/docreader.proto",
}
