// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/docreader.proto

package docreader

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkStrategy int32

const (
	ChunkStrategy_PARAGRAPH  ChunkStrategy = 0 // 按段落分块
	ChunkStrategy_SENTENCE   ChunkStrategy = 1 // 按句子分块
	ChunkStrategy_FIXED_SIZE ChunkStrategy = 2 // 固定大小
	ChunkStrategy_SEMANTIC   ChunkStrategy = 3 // 语义分块
	ChunkStrategy_RECURSIVE  ChunkStrategy = 4 // 递归分块
)

// Enum value maps for ChunkStrategy.
var (
	ChunkStrategy_name = map[int32]string{
		0: "PARAGRAPH",
		1: "SENTENCE",
		2: "FIXED_SIZE",
		3: "SEMANTIC",
		4: "RECURSIVE",
	}
	ChunkStrategy_value = map[string]int32{
		"PARAGRAPH":  0,
		"SENTENCE":   1,
		"FIXED_SIZE": 2,
		"SEMANTIC":   3,
		"RECURSIVE":  4,
	}
)

func (x ChunkStrategy) Enum() *ChunkStrategy {
	p := new(ChunkStrategy)
	*p = x
	return p
}

func (x ChunkStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_docreader_proto_enumTypes[0].Descriptor()
}

func (ChunkStrategy) Type() protoreflect.EnumType {
	return &file_proto_docreader_proto_enumTypes[0]
}

func (x ChunkStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkStrategy.Descriptor instead.
func (ChunkStrategy) EnumDescriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{0}
}

type ParseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*ParseRequest_FilePath
	//	*ParseRequest_Url
	//	*ParseRequest_Content
	Source        isParseRequest_Source `protobuf_oneof:"source"`
	Format        string                `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"` // 格式（自动检测或指定：pdf, docx, xlsx, csv, md, txt）
	Options       *ParseOptions         `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_proto_docreader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetSource() isParseRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ParseRequest) GetFilePath() string {
	if x != nil {
		if x, ok := x.Source.(*ParseRequest_FilePath); ok {
			return x.FilePath
		}
	}
	return ""
}

func (x *ParseRequest) GetUrl() string {
	if x != nil {
		if x, ok := x.Source.(*ParseRequest_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *ParseRequest) GetContent() []byte {
	if x != nil {
		if x, ok := x.Source.(*ParseRequest_Content); ok {
			return x.Content
		}
	}
	return nil
}

func (x *ParseRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ParseRequest) GetOptions() *ParseOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type isParseRequest_Source interface {
	isParseRequest_Source()
}

type ParseRequest_FilePath struct {
	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3,oneof"` // 文件路径
}

type ParseRequest_Url struct {
	Url string `protobuf:"bytes,2,opt,name=url,proto3,oneof"` // URL
}

type ParseRequest_Content struct {
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3,oneof"` // 直接内容
}

func (*ParseRequest_FilePath) isParseRequest_Source() {}

func (*ParseRequest_Url) isParseRequest_Source() {}

func (*ParseRequest_Content) isParseRequest_Source() {}

type ParseOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeMetadata bool                   `protobuf:"varint,1,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"` // 是否包含元数据
	ExtractTables   bool                   `protobuf:"varint,2,opt,name=extract_tables,json=extractTables,proto3" json:"extract_tables,omitempty"`       // 是否提取表格
	ExtractImages   bool                   `protobuf:"varint,3,opt,name=extract_images,json=extractImages,proto3" json:"extract_images,omitempty"`       // 是否提取图片
	OcrEngine       string                 `protobuf:"bytes,4,opt,name=ocr_engine,json=ocrEngine,proto3" json:"ocr_engine,omitempty"`                    // OCR 引擎：paddleocr | vlm
	Language        string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`                                       // OCR 语言：chi_sim | eng
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ParseOptions) Reset() {
	*x = ParseOptions{}
	mi := &file_proto_docreader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseOptions) ProtoMessage() {}

func (x *ParseOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseOptions.ProtoReflect.Descriptor instead.
func (*ParseOptions) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{1}
}

func (x *ParseOptions) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

func (x *ParseOptions) GetExtractTables() bool {
	if x != nil {
		return x.ExtractTables
	}
	return false
}

func (x *ParseOptions) GetExtractImages() bool {
	if x != nil {
		return x.ExtractImages
	}
	return false
}

func (x *ParseOptions) GetOcrEngine() string {
	if x != nil {
		return x.OcrEngine
	}
	return ""
}

func (x *ParseOptions) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"` // 提取的文本
	Metadata      *DocumentMetadata      `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Tables        []*TableData           `protobuf:"bytes,4,rep,name=tables,proto3" json:"tables,omitempty"` // 提取的表格
	Images        []*ImageInfo           `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"` // 提取的图片信息
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_proto_docreader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{2}
}

func (x *ParseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ParseResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ParseResponse) GetMetadata() *DocumentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ParseResponse) GetTables() []*TableData {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *ParseResponse) GetImages() []*ImageInfo {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ParseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DocumentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`                                                                                   // 文档格式
	PageCount     int32                  `protobuf:"varint,2,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`                                                           // 页数
	CharCount     int32                  `protobuf:"varint,3,opt,name=char_count,json=charCount,proto3" json:"char_count,omitempty"`                                                           // 字符数
	Properties    map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 其他属性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentMetadata) Reset() {
	*x = DocumentMetadata{}
	mi := &file_proto_docreader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentMetadata) ProtoMessage() {}

func (x *DocumentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentMetadata.ProtoReflect.Descriptor instead.
func (*DocumentMetadata) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{3}
}

func (x *DocumentMetadata) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *DocumentMetadata) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *DocumentMetadata) GetCharCount() int32 {
	if x != nil {
		return x.CharCount
	}
	return 0
}

func (x *DocumentMetadata) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type TableData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	TableIndex    int32                  `protobuf:"varint,2,opt,name=table_index,json=tableIndex,proto3" json:"table_index,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	Markdown      string                 `protobuf:"bytes,4,opt,name=markdown,proto3" json:"markdown,omitempty"` // Markdown 格式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableData) Reset() {
	*x = TableData{}
	mi := &file_proto_docreader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableData) ProtoMessage() {}

func (x *TableData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableData.ProtoReflect.Descriptor instead.
func (*TableData) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{4}
}

func (x *TableData) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TableData) GetTableIndex() int32 {
	if x != nil {
		return x.TableIndex
	}
	return 0
}

func (x *TableData) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *TableData) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []string               `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_proto_docreader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{5}
}

func (x *Row) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	ImageIndex    int32                  `protobuf:"varint,2,opt,name=image_index,json=imageIndex,proto3" json:"image_index,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"` // 图片保存路径（如果提取）
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_proto_docreader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{6}
}

func (x *ImageInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ImageInfo) GetImageIndex() int32 {
	if x != nil {
		return x.ImageIndex
	}
	return 0
}

func (x *ImageInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ImageInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ParseBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*ParseRequest        `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseBatchRequest) Reset() {
	*x = ParseBatchRequest{}
	mi := &file_proto_docreader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseBatchRequest) ProtoMessage() {}

func (x *ParseBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseBatchRequest.ProtoReflect.Descriptor instead.
func (*ParseBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{7}
}

func (x *ParseBatchRequest) GetRequests() []*ParseRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ParseBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*ParseResponse       `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseBatchResponse) Reset() {
	*x = ParseBatchResponse{}
	mi := &file_proto_docreader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseBatchResponse) ProtoMessage() {}

func (x *ParseBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseBatchResponse.ProtoReflect.Descriptor instead.
func (*ParseBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{8}
}

func (x *ParseBatchResponse) GetResponses() []*ParseResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type OCRRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*OCRRequest_FilePath
	//	*OCRRequest_ImageData
	//	*OCRRequest_Url
	Source        isOCRRequest_Source `protobuf_oneof:"source"`
	Engine        string              `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"`     // paddleocr | vlm
	Language      string              `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"` // chi_sim | eng
	Options       *OCROptions         `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCRRequest) Reset() {
	*x = OCRRequest{}
	mi := &file_proto_docreader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRRequest) ProtoMessage() {}

func (x *OCRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRRequest.ProtoReflect.Descriptor instead.
func (*OCRRequest) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{9}
}

func (x *OCRRequest) GetSource() isOCRRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *OCRRequest) GetFilePath() string {
	if x != nil {
		if x, ok := x.Source.(*OCRRequest_FilePath); ok {
			return x.FilePath
		}
	}
	return ""
}

func (x *OCRRequest) GetImageData() []byte {
	if x != nil {
		if x, ok := x.Source.(*OCRRequest_ImageData); ok {
			return x.ImageData
		}
	}
	return nil
}

func (x *OCRRequest) GetUrl() string {
	if x != nil {
		if x, ok := x.Source.(*OCRRequest_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *OCRRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *OCRRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *OCRRequest) GetOptions() *OCROptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type isOCRRequest_Source interface {
	isOCRRequest_Source()
}

type OCRRequest_FilePath struct {
	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3,oneof"`
}

type OCRRequest_ImageData struct {
	ImageData []byte `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3,oneof"`
}

type OCRRequest_Url struct {
	Url string `protobuf:"bytes,3,opt,name=url,proto3,oneof"`
}

func (*OCRRequest_FilePath) isOCRRequest_Source() {}

func (*OCRRequest_ImageData) isOCRRequest_Source() {}

func (*OCRRequest_Url) isOCRRequest_Source() {}

type OCROptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Det           bool                   `protobuf:"varint,1,opt,name=det,proto3" json:"det,omitempty"`                                          // 是否检测方向
	Rec           bool                   `protobuf:"varint,2,opt,name=rec,proto3" json:"rec,omitempty"`                                          // 是否识别文字
	UseCls        bool                   `protobuf:"varint,3,opt,name=use_cls,json=useCls,proto3" json:"use_cls,omitempty"`                      // 是否使用方向分类
	ReturnDetails bool                   `protobuf:"varint,4,opt,name=return_details,json=returnDetails,proto3" json:"return_details,omitempty"` // 是否返回详细信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCROptions) Reset() {
	*x = OCROptions{}
	mi := &file_proto_docreader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCROptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCROptions) ProtoMessage() {}

func (x *OCROptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCROptions.ProtoReflect.Descriptor instead.
func (*OCROptions) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{10}
}

func (x *OCROptions) GetDet() bool {
	if x != nil {
		return x.Det
	}
	return false
}

func (x *OCROptions) GetRec() bool {
	if x != nil {
		return x.Rec
	}
	return false
}

func (x *OCROptions) GetUseCls() bool {
	if x != nil {
		return x.UseCls
	}
	return false
}

func (x *OCROptions) GetReturnDetails() bool {
	if x != nil {
		return x.ReturnDetails
	}
	return false
}

type OCRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Blocks        []*OCRBlock            `protobuf:"bytes,3,rep,name=blocks,proto3" json:"blocks,omitempty"` // 详细信息
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCRResponse) Reset() {
	*x = OCRResponse{}
	mi := &file_proto_docreader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRResponse) ProtoMessage() {}

func (x *OCRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRResponse.ProtoReflect.Descriptor instead.
func (*OCRResponse) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{11}
}

func (x *OCRResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OCRResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OCRResponse) GetBlocks() []*OCRBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *OCRResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *OCRResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OCRBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Box           *Rect                  `protobuf:"bytes,1,opt,name=box,proto3" json:"box,omitempty"` // 文本框位置
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCRBlock) Reset() {
	*x = OCRBlock{}
	mi := &file_proto_docreader_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRBlock) ProtoMessage() {}

func (x *OCRBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRBlock.ProtoReflect.Descriptor instead.
func (*OCRBlock) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{12}
}

func (x *OCRBlock) GetBox() *Rect {
	if x != nil {
		return x.Box
	}
	return nil
}

func (x *OCRBlock) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OCRBlock) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type Rect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rect) Reset() {
	*x = Rect{}
	mi := &file_proto_docreader_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{13}
}

func (x *Rect) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Rect) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Rect) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Rect) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type OCRBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*OCRRequest          `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCRBatchRequest) Reset() {
	*x = OCRBatchRequest{}
	mi := &file_proto_docreader_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRBatchRequest) ProtoMessage() {}

func (x *OCRBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRBatchRequest.ProtoReflect.Descriptor instead.
func (*OCRBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{14}
}

func (x *OCRBatchRequest) GetRequests() []*OCRRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type OCRBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Response      *OCRResponse           `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCRBatchResponse) Reset() {
	*x = OCRBatchResponse{}
	mi := &file_proto_docreader_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRBatchResponse) ProtoMessage() {}

func (x *OCRBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRBatchResponse.ProtoReflect.Descriptor instead.
func (*OCRBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{15}
}

func (x *OCRBatchResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OCRBatchResponse) GetResponse() *OCRResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type ChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                                       // 待分块的文本
	Strategy      ChunkStrategy          `protobuf:"varint,2,opt,name=strategy,proto3,enum=docreader.ChunkStrategy" json:"strategy,omitempty"` // 分块策略
	Options       *ChunkOptions          `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRequest) Reset() {
	*x = ChunkRequest{}
	mi := &file_proto_docreader_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRequest) ProtoMessage() {}

func (x *ChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRequest.ProtoReflect.Descriptor instead.
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{16}
}

func (x *ChunkRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChunkRequest) GetStrategy() ChunkStrategy {
	if x != nil {
		return x.Strategy
	}
	return ChunkStrategy_PARAGRAPH
}

func (x *ChunkRequest) GetOptions() *ChunkOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ChunkOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkSize     int32                  `protobuf:"varint,1,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`            // 块大小（字符数）
	ChunkOverlap  int32                  `protobuf:"varint,2,opt,name=chunk_overlap,json=chunkOverlap,proto3" json:"chunk_overlap,omitempty"`   // 重叠大小
	Separator     string                 `protobuf:"bytes,3,opt,name=separator,proto3" json:"separator,omitempty"`                              // 分隔符
	MinChunkSize  int32                  `protobuf:"varint,4,opt,name=min_chunk_size,json=minChunkSize,proto3" json:"min_chunk_size,omitempty"` // 最小块大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkOptions) Reset() {
	*x = ChunkOptions{}
	mi := &file_proto_docreader_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkOptions) ProtoMessage() {}

func (x *ChunkOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkOptions.ProtoReflect.Descriptor instead.
func (*ChunkOptions) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{17}
}

func (x *ChunkOptions) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *ChunkOptions) GetChunkOverlap() int32 {
	if x != nil {
		return x.ChunkOverlap
	}
	return 0
}

func (x *ChunkOptions) GetSeparator() string {
	if x != nil {
		return x.Separator
	}
	return ""
}

func (x *ChunkOptions) GetMinChunkSize() int32 {
	if x != nil {
		return x.MinChunkSize
	}
	return 0
}

type ChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*Chunk               `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkResponse) Reset() {
	*x = ChunkResponse{}
	mi := &file_proto_docreader_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkResponse) ProtoMessage() {}

func (x *ChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkResponse.ProtoReflect.Descriptor instead.
func (*ChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{18}
}

func (x *ChunkResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ChunkResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	StartPos      int32                  `protobuf:"varint,3,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"`
	EndPos        int32                  `protobuf:"varint,4,opt,name=end_pos,json=endPos,proto3" json:"end_pos,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_proto_docreader_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{19}
}

func (x *Chunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Chunk) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Chunk) GetStartPos() int32 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *Chunk) GetEndPos() int32 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

func (x *Chunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FetchURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Options       *FetchOptions          `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchURLRequest) Reset() {
	*x = FetchURLRequest{}
	mi := &file_proto_docreader_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchURLRequest) ProtoMessage() {}

func (x *FetchURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchURLRequest.ProtoReflect.Descriptor instead.
func (*FetchURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{20}
}

func (x *FetchURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchURLRequest) GetOptions() *FetchOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type FetchOptions struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timeout           int32                  `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"`                                                // 超时时间（秒）
	WaitForJavascript bool                   `protobuf:"varint,2,opt,name=wait_for_javascript,json=waitForJavascript,proto3" json:"wait_for_javascript,omitempty"` // 是否等待 JS 执行
	WaitTime          int32                  `protobuf:"varint,3,opt,name=wait_time,json=waitTime,proto3" json:"wait_time,omitempty"`                              // 等待时间（毫秒）
	Screenshot        bool                   `protobuf:"varint,4,opt,name=screenshot,proto3" json:"screenshot,omitempty"`                                          // 是否截图
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FetchOptions) Reset() {
	*x = FetchOptions{}
	mi := &file_proto_docreader_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOptions) ProtoMessage() {}

func (x *FetchOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOptions.ProtoReflect.Descriptor instead.
func (*FetchOptions) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{21}
}

func (x *FetchOptions) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *FetchOptions) GetWaitForJavascript() bool {
	if x != nil {
		return x.WaitForJavascript
	}
	return false
}

func (x *FetchOptions) GetWaitTime() int32 {
	if x != nil {
		return x.WaitTime
	}
	return 0
}

func (x *FetchOptions) GetScreenshot() bool {
	if x != nil {
		return x.Screenshot
	}
	return false
}

type FetchURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`             // 提取的文本
	Html          string                 `protobuf:"bytes,3,opt,name=html,proto3" json:"html,omitempty"`             // 原始 HTML
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`           // 页面标题
	Links         []string               `protobuf:"bytes,5,rep,name=links,proto3" json:"links,omitempty"`           // 页面链接
	Screenshot    []byte                 `protobuf:"bytes,6,opt,name=screenshot,proto3" json:"screenshot,omitempty"` // 截图
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchURLResponse) Reset() {
	*x = FetchURLResponse{}
	mi := &file_proto_docreader_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchURLResponse) ProtoMessage() {}

func (x *FetchURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docreader_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchURLResponse.ProtoReflect.Descriptor instead.
func (*FetchURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_docreader_proto_rawDescGZIP(), []int{22}
}

func (x *FetchURLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FetchURLResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *FetchURLResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *FetchURLResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FetchURLResponse) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *FetchURLResponse) GetScreenshot() []byte {
	if x != nil {
		return x.Screenshot
	}
	return nil
}

func (x *FetchURLResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_docreader_proto protoreflect.FileDescriptor

const file_proto_docreader_proto_rawDesc = "" +
	"\n" +
	"\x15proto/docreader.proto\x12\tdocreader\"\xb2\x01\n" +
	"\fParseRequest\x12\x1d\n" +
	"\tfile_path\x18\x01 \x01(\tH\x00R\bfilePath\x12\x12\n" +
	"\x03url\x18\x02 \x01(\tH\x00R\x03url\x12\x1a\n" +
	"\acontent\x18\x03 \x01(\fH\x00R\acontent\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x121\n" +
	"\aoptions\x18\x05 \x01(\v2\x17.docreader.ParseOptionsR\aoptionsB\b\n" +
	"\x06source\"\xc2\x01\n" +
	"\fParseOptions\x12)\n" +
	"\x10include_metadata\x18\x01 \x01(\bR\x0fincludeMetadata\x12%\n" +
	"\x0eextract_tables\x18\x02 \x01(\bR\rextractTables\x12%\n" +
	"\x0eextract_images\x18\x03 \x01(\bR\rextractImages\x12\x1d\n" +
	"\n" +
	"ocr_engine\x18\x04 \x01(\tR\tocrEngine\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\"\xe8\x01\n" +
	"\rParseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x127\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1b.docreader.DocumentMetadataR\bmetadata\x12,\n" +
	"\x06tables\x18\x04 \x03(\v2\x14.docreader.TableDataR\x06tables\x12,\n" +
	"\x06images\x18\x05 \x03(\v2\x14.docreader.ImageInfoR\x06images\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xf4\x01\n" +
	"\x10DocumentMetadata\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"page_count\x18\x02 \x01(\x05R\tpageCount\x12\x1d\n" +
	"\n" +
	"char_count\x18\x03 \x01(\x05R\tcharCount\x12K\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2+.docreader.DocumentMetadata.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x01\n" +
	"\tTableData\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtable_index\x18\x02 \x01(\x05R\n" +
	"tableIndex\x12\"\n" +
	"\x04rows\x18\x03 \x03(\v2\x0e.docreader.RowR\x04rows\x12\x1a\n" +
	"\bmarkdown\x18\x04 \x01(\tR\bmarkdown\"\x1b\n" +
	"\x03Row\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells\"\x82\x01\n" +
	"\tImageInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1f\n" +
	"\vimage_index\x18\x02 \x01(\x05R\n" +
	"imageIndex\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\"H\n" +
	"\x11ParseBatchRequest\x123\n" +
	"\brequests\x18\x01 \x03(\v2\x17.docreader.ParseRequestR\brequests\"L\n" +
	"\x12ParseBatchResponse\x126\n" +
	"\tresponses\x18\x01 \x03(\v2\x18.docreader.ParseResponseR\tresponses\"\xcf\x01\n" +
	"\n" +
	"OCRRequest\x12\x1d\n" +
	"\tfile_path\x18\x01 \x01(\tH\x00R\bfilePath\x12\x1f\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fH\x00R\timageData\x12\x12\n" +
	"\x03url\x18\x03 \x01(\tH\x00R\x03url\x12\x16\n" +
	"\x06engine\x18\x04 \x01(\tR\x06engine\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12/\n" +
	"\aoptions\x18\x06 \x01(\v2\x15.docreader.OCROptionsR\aoptionsB\b\n" +
	"\x06source\"p\n" +
	"\n" +
	"OCROptions\x12\x10\n" +
	"\x03det\x18\x01 \x01(\bR\x03det\x12\x10\n" +
	"\x03rec\x18\x02 \x01(\bR\x03rec\x12\x17\n" +
	"\ause_cls\x18\x03 \x01(\bR\x06useCls\x12%\n" +
	"\x0ereturn_details\x18\x04 \x01(\bR\rreturnDetails\"\x9e\x01\n" +
	"\vOCRResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12+\n" +
	"\x06blocks\x18\x03 \x03(\v2\x13.docreader.OCRBlockR\x06blocks\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"a\n" +
	"\bOCRBlock\x12!\n" +
	"\x03box\x18\x01 \x01(\v2\x0f.docreader.RectR\x03box\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\"P\n" +
	"\x04Rect\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"D\n" +
	"\x0fOCRBatchRequest\x121\n" +
	"\brequests\x18\x01 \x03(\v2\x15.docreader.OCRRequestR\brequests\"\\\n" +
	"\x10OCRBatchResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x122\n" +
	"\bresponse\x18\x02 \x01(\v2\x16.docreader.OCRResponseR\bresponse\"\x8b\x01\n" +
	"\fChunkRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x124\n" +
	"\bstrategy\x18\x02 \x01(\x0e2\x18.docreader.ChunkStrategyR\bstrategy\x121\n" +
	"\aoptions\x18\x03 \x01(\v2\x17.docreader.ChunkOptionsR\aoptions\"\x96\x01\n" +
	"\fChunkOptions\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x01 \x01(\x05R\tchunkSize\x12#\n" +
	"\rchunk_overlap\x18\x02 \x01(\x05R\fchunkOverlap\x12\x1c\n" +
	"\tseparator\x18\x03 \x01(\tR\tseparator\x12$\n" +
	"\x0emin_chunk_size\x18\x04 \x01(\x05R\fminChunkSize\"Z\n" +
	"\rChunkResponse\x12(\n" +
	"\x06chunks\x18\x01 \x03(\v2\x10.docreader.ChunkR\x06chunks\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xe0\x01\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x1b\n" +
	"\tstart_pos\x18\x03 \x01(\x05R\bstartPos\x12\x17\n" +
	"\aend_pos\x18\x04 \x01(\x05R\x06endPos\x12:\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1e.docreader.Chunk.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\x0fFetchURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x121\n" +
	"\aoptions\x18\x02 \x01(\v2\x17.docreader.FetchOptionsR\aoptions\"\x95\x01\n" +
	"\fFetchOptions\x12\x18\n" +
	"\atimeout\x18\x01 \x01(\x05R\atimeout\x12.\n" +
	"\x13wait_for_javascript\x18\x02 \x01(\bR\x11waitForJavascript\x12\x1b\n" +
	"\twait_time\x18\x03 \x01(\x05R\bwaitTime\x12\x1e\n" +
	"\n" +
	"screenshot\x18\x04 \x01(\bR\n" +
	"screenshot\"\xb6\x01\n" +
	"\x10FetchURLResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04html\x18\x03 \x01(\tR\x04html\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x14\n" +
	"\x05links\x18\x05 \x03(\tR\x05links\x12\x1e\n" +
	"\n" +
	"screenshot\x18\x06 \x01(\fR\n" +
	"screenshot\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error*Y\n" +
	"\rChunkStrategy\x12\r\n" +
	"\tPARAGRAPH\x10\x00\x12\f\n" +
	"\bSENTENCE\x10\x01\x12\x0e\n" +
	"\n" +
	"FIXED_SIZE\x10\x02\x12\f\n" +
	"\bSEMANTIC\x10\x03\x12\r\n" +
	"\tRECURSIVE\x10\x042\xb1\x03\n" +
	"\x15DocumentReaderService\x12B\n" +
	"\rParseDocument\x12\x17.docreader.ParseRequest\x1a\x18.docreader.ParseResponse\x12I\n" +
	"\n" +
	"ParseBatch\x12\x1c.docreader.ParseBatchRequest\x1a\x1d.docreader.ParseBatchResponse\x129\n" +
	"\bOCRImage\x12\x15.docreader.OCRRequest\x1a\x16.docreader.OCRResponse\x12E\n" +
	"\bOCRBatch\x12\x1a.docreader.OCRBatchRequest\x1a\x1b.docreader.OCRBatchResponse0\x01\x12B\n" +
	"\rChunkDocument\x12\x17.docreader.ChunkRequest\x1a\x18.docreader.ChunkResponse\x12C\n" +
	"\bFetchURL\x12\x1a.docreader.FetchURLRequest\x1a\x1b.docreader.FetchURLResponseB\x1aZ\x18link/api/proto/docreaderb\x06proto3"

var (
	file_proto_docreader_proto_rawDescOnce sync.Once
	file_proto_docreader_proto_rawDescData []byte
)

func file_proto_docreader_proto_rawDescGZIP() []byte {
	file_proto_docreader_proto_rawDescOnce.Do(func() {
		file_proto_docreader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_docreader_proto_rawDesc), len(file_proto_docreader_proto_rawDesc)))
	})
	return file_proto_docreader_proto_rawDescData
}

var file_proto_docreader_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_docreader_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_docreader_proto_goTypes = []any{
	(ChunkStrategy)(0),         // 0: docreader.ChunkStrategy
	(*ParseRequest)(nil),       // 1: docreader.ParseRequest
	(*ParseOptions)(nil),       // 2: docreader.ParseOptions
	(*ParseResponse)(nil),      // 3: docreader.ParseResponse
	(*DocumentMetadata)(nil),   // 4: docreader.DocumentMetadata
	(*TableData)(nil),          // 5: docreader.TableData
	(*Row)(nil),                // 6: docreader.Row
	(*ImageInfo)(nil),          // 7: docreader.ImageInfo
	(*ParseBatchRequest)(nil),  // 8: docreader.ParseBatchRequest
	(*ParseBatchResponse)(nil), // 9: docreader.ParseBatchResponse
	(*OCRRequest)(nil),         // 10: docreader.OCRRequest
	(*OCROptions)(nil),         // 11: docreader.OCROptions
	(*OCRResponse)(nil),        // 12: docreader.OCRResponse
	(*OCRBlock)(nil),           // 13: docreader.OCRBlock
	(*Rect)(nil),               // 14: docreader.Rect
	(*OCRBatchRequest)(nil),    // 15: docreader.OCRBatchRequest
	(*OCRBatchResponse)(nil),   // 16: docreader.OCRBatchResponse
	(*ChunkRequest)(nil),       // 17: docreader.ChunkRequest
	(*ChunkOptions)(nil),       // 18: docreader.ChunkOptions
	(*ChunkResponse)(nil),      // 19: docreader.ChunkResponse
	(*Chunk)(nil),              // 20: docreader.Chunk
	(*FetchURLRequest)(nil),    // 21: docreader.FetchURLRequest
	(*FetchOptions)(nil),       // 22: docreader.FetchOptions
	(*FetchURLResponse)(nil),   // 23: docreader.FetchURLResponse
	nil,                        // 24: docreader.DocumentMetadata.PropertiesEntry
	nil,                        // 25: docreader.Chunk.MetadataEntry
}
var file_proto_docreader_proto_depIdxs = []int32{
	2,  // 0: docreader.ParseRequest.options:type_name -> docreader.ParseOptions
	4,  // 1: docreader.ParseResponse.metadata:type_name -> docreader.DocumentMetadata
	5,  // 2: docreader.ParseResponse.tables:type_name -> docreader.TableData
	7,  // 3: docreader.ParseResponse.images:type_name -> docreader.ImageInfo
	24, // 4: docreader.DocumentMetadata.properties:type_name -> docreader.DocumentMetadata.PropertiesEntry
	6,  // 5: docreader.TableData.rows:type_name -> docreader.Row
	1,  // 6: docreader.ParseBatchRequest.requests:type_name -> docreader.ParseRequest
	3,  // 7: docreader.ParseBatchResponse.responses:type_name -> docreader.ParseResponse
	11, // 8: docreader.OCRRequest.options:type_name -> docreader.OCROptions
	13, // 9: docreader.OCRResponse.blocks:type_name -> docreader.OCRBlock
	14, // 10: docreader.OCRBlock.box:type_name -> docreader.Rect
	10, // 11: docreader.OCRBatchRequest.requests:type_name -> docreader.OCRRequest
	12, // 12: docreader.OCRBatchResponse.response:type_name -> docreader.OCRResponse
	0,  // 13: docreader.ChunkRequest.strategy:type_name -> docreader.ChunkStrategy
	18, // 14: docreader.ChunkRequest.options:type_name -> docreader.ChunkOptions
	20, // 15: docreader.ChunkResponse.chunks:type_name -> docreader.Chunk
	25, // 16: docreader.Chunk.metadata:type_name -> docreader.Chunk.MetadataEntry
	22, // 17: docreader.FetchURLRequest.options:type_name -> docreader.FetchOptions
	1,  // 18: docreader.DocumentReaderService.ParseDocument:input_type -> docreader.ParseRequest
	8,  // 19: docreader.DocumentReaderService.ParseBatch:input_type -> docreader.ParseBatchRequest
	10, // 20: docreader.DocumentReaderService.OCRImage:input_type -> docreader.OCRRequest
	15, // 21: docreader.DocumentReaderService.OCRBatch:input_type -> docreader.OCRBatchRequest
	17, // 22: docreader.DocumentReaderService.ChunkDocument:input_type -> docreader.ChunkRequest
	21, // 23: docreader.DocumentReaderService.FetchURL:input_type -> docreader.FetchURLRequest
	3,  // 24: docreader.DocumentReaderService.ParseDocument:output_type -> docreader.ParseResponse
	9,  // 25: docreader.DocumentReaderService.ParseBatch:output_type -> docreader.ParseBatchResponse
	12, // 26: docreader.DocumentReaderService.OCRImage:output_type -> docreader.OCRResponse
	16, // 27: docreader.DocumentReaderService.OCRBatch:output_type -> docreader.OCRBatchResponse
	19, // 28: docreader.DocumentReaderService.ChunkDocument:output_type -> docreader.ChunkResponse
	23, // 29: docreader.DocumentReaderService.FetchURL:output_type -> docreader.FetchURLResponse
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_docreader_proto_init() }
func file_proto_docreader_proto_init() {
	if File_proto_docreader_proto != nil {
		return
	}
	file_proto_docreader_proto_msgTypes[0].OneofWrappers = []any{
		(*ParseRequest_FilePath)(nil),
		(*ParseRequest_Url)(nil),
		(*ParseRequest_Content)(nil),
	}
	file_proto_docreader_proto_msgTypes[9].OneofWrappers = []any{
		(*OCRRequest_FilePath)(nil),
		(*OCRRequest_ImageData)(nil),
		(*OCRRequest_Url)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_docreader_proto_rawDesc), len(file_proto_docreader_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_docreader_proto_goTypes,
		DependencyIndexes: file_proto_docreader_proto_depIdxs,
		EnumInfos:         file_proto_docreader_proto_enumTypes,
		MessageInfos:      file_proto_docreader_proto_msgTypes,
	}.Build()
	File_proto_docreader_proto = out.File
	file_proto_docreader_proto_goTypes = nil
	file_proto_docreader_proto_depIdxs = nil
}
