// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"fmt"
	"github.com/cloudwego/eino/components/embedding"
	"github.com/cloudwego/eino/components/model"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"link/internal/handler"
	"link/internal/handler/middleware"
	"link/internal/handler/router"
	"link/internal/handler/web"
	"link/internal/infrastructure/cache/evaluation"
	redis2 "link/internal/infrastructure/cache/redis"
	"link/internal/infrastructure/config"
	"link/internal/infrastructure/graph"
	"link/internal/infrastructure/grpc/docreader"
	quality2 "link/internal/infrastructure/grpc/quality"
	"link/internal/infrastructure/id"
	llm2 "link/internal/infrastructure/llm"
	chat2 "link/internal/infrastructure/llm/chat"
	embedding2 "link/internal/infrastructure/llm/embedding"
	"link/internal/infrastructure/queue"
	"link/internal/model/agent"
	audit2 "link/internal/model/audit"
	"link/internal/model/common"
	"link/internal/model/conversation"
	"link/internal/model/datasource"
	evaluation2 "link/internal/model/evaluation"
	"link/internal/model/knowledge"
	"link/internal/model/llm"
	quality3 "link/internal/model/quality"
	"link/internal/model/rag"
	"link/internal/model/semantic"
	"link/internal/model/task"
	"link/internal/model/tenant"
	domaintrace "link/internal/model/trace"
	"link/internal/model/user"
	"link/internal/repository/milvus/retriever"
	"link/internal/repository/mysql"
	neo4j2 "link/internal/repository/neo4j"
	"link/internal/service/account"
	agent2 "link/internal/service/agent"
	"link/internal/service/agent/framework"
	"link/internal/service/agent/tools"
	"link/internal/service/audit"
	"link/internal/service/chat"
	datasource2 "link/internal/service/datasource"
	"link/internal/service/evaluation"
	"link/internal/service/evaluation/executor"
	knowledge2 "link/internal/service/knowledge"
	rag2 "link/internal/service/knowledge/pipeline"
	"link/internal/service/quality"
	semantic2 "link/internal/service/semantic"
	"log"
	"time"
)

// Injectors from wire.go:

//go:generate wire
func InitializeApp(db *gorm.DB) (*App, error) {
	userRepository := ProvideUserRepository(db)
	refreshTokenRepository := ProvideRefreshTokenRepository(db)
	jwtConfig := ProvideJWTConfig()
	tenantRepository := ProvideTenantRepository(db)
	accountService := ProvideAccountService(userRepository, refreshTokenRepository, jwtConfig, tenantRepository)
	authHandler := ProvideAuthHandler(accountService)
	knowledgeBaseRepository := ProvideKnowledgeBaseRepository(db)
	knowledgeBaseSettingRepository := ProvideKnowledgeBaseSettingRepository(db)
	knowledgeRepository := ProvideKnowledgeRepository(db)
	chunkRepository := ProvideChunkRepository(db)
	knowledgeStatsQuerier := ProvideKnowledgeStatsQuerier(db)
	embeddingConfig := ProvideEmbeddingConfig()
	embedder, err := ProvideEmbedder(embeddingConfig)
	if err != nil {
		return nil, err
	}
	vectorRetriever, err := ProvideVectorRetriever(embedder)
	if err != nil {
		return nil, err
	}
	vectorRepository := ProvideVectorRepository(vectorRetriever)
	neo4jConfig := ProvideNeo4jConfig()
	driverWithContext, err := ProvideNeo4jDriver(neo4jConfig)
	if err != nil {
		return nil, err
	}
	graphRepository, err := ProvideNeo4jGraphRepository(driverWithContext, neo4jConfig)
	if err != nil {
		return nil, err
	}
	knowledgeBaseService := ProvideKnowledgeBaseService(knowledgeBaseRepository, knowledgeBaseSettingRepository, knowledgeRepository, chunkRepository, knowledgeStatsQuerier, vectorRepository, graphRepository)
	client, err := ProvideDocReaderClient()
	if err != nil {
		return nil, err
	}
	chatConfig := ProvideChatConfig()
	llmClient := ProvideLLMClient(chatConfig)
	idGenerator := ProvideIDGenerator()
	documentProcessorService := ProvideDocumentProcessorService(knowledgeBaseRepository, knowledgeRepository, chunkRepository, vectorRepository, graphRepository, client, embedder, llmClient, idGenerator)
	milvusRetriever := ProvideMilvusRetriever()
	ragGraphRepository := ProvideRAGGraphRepository()
	graphQueryRepository := ProvideGraphQueryRepository(db)
	retriever := ProvideRetriever(knowledgeBaseSettingRepository, chunkRepository, embedder, milvusRetriever, ragGraphRepository, graphQueryRepository)
	retrievalCapability := ProvideRetrievalCapability(retriever)
	knowledgeBaseHandler := ProvideKnowledgeBaseHandler(knowledgeBaseService, documentProcessorService, retrievalCapability)
	sessionRepository := ProvideSessionRepository(db)
	messageRepository := ProvideMessageRepository(db)
	retrievalSettingRepository := ProvideRetrievalSettingRepository(db)
	sessionService := ProvideSessionService(sessionRepository, messageRepository, retrievalSettingRepository)
	modelRepository := ProvideModelRepository(db)
	modelFactory := ProvideModelFactory()
	chatService := ProvideChatService(llmClient, modelRepository, modelFactory)
	sessionHandler := ProvideSessionHandler(sessionService, chatService)
	messageService := ProvideMessageService(messageRepository)
	messageHandler := ProvideMessageHandler(messageService)
	chatHandler := ProvideChatHandler(chatService)
	tenantHandler := ProvideTenantHandler(accountService)
	specRegistry := ProvideAgentRegistry()
	agentExecutor := ProvideAgentOrchestrator(specRegistry)
	executeService := ProvideExecuteService(agentExecutor)
	researchService := ProvideResearchService(agentExecutor)
	configService := ProvideConfigService()
	progressService := ProvideProgressService()
	agentPersistenceService := ProvideAgentPersistenceService(sessionRepository, messageRepository)
	agentHandler := ProvideAgentHandler(executeService, researchService, configService, progressService, agentPersistenceService, retrievalSettingRepository)
	registryAgentHandler := ProvideRegistryAgentHandler(specRegistry)
	llmChat := ProvideRAGLLMChat(llmClient)
	graphService := ProvideGraphService(graphRepository, graphQueryRepository, llmChat)
	graphHandler := ProvideGraphHandler(graphService)
	modelService := ProvideModelService(modelRepository, modelFactory)
	modelHandler := ProvideModelHandler(modelService, chatService)
	taskRepository := ProvideTaskRepository(db)
	redisConfig := ProvideRedisConfig()
	redisClient, err := ProvideRedisClient(redisConfig)
	if err != nil {
		return nil, err
	}
	taskQueue := ProvideTaskQueue(redisClient)
	taskService := ProvideTaskService(taskRepository, taskQueue)
	taskHandler := ProvideTaskHandler(taskService)
	chatModel := ProvideChatModel(chatConfig)
	ragOptimizerHandler := ProvideRAGOptimizerHandler(chatModel, retriever)
	guardrailHandler := ProvideGuardrailHandler(chatModel)
	datasetRepository := ProvideDatasetRepository(db)
	datasetLoader := ProvideDatasetLoader(db, datasetRepository)
	datasetService := ProvideDatasetService(datasetLoader)
	evaluationTaskRepository := ProvideEvaluationTaskRepository(db)
	evaluationResultRepository := ProvideEvaluationResultRepository(db)
	progressCache := ProvideEvaluationProgressCache(redisClient)
	evaluationQueue := ProvideEvaluationQueue(redisClient)
	evaluationConfig := ProvideEvaluationConfig()
	service := ProvideEvaluationService(datasetService, evaluationTaskRepository, evaluationResultRepository, progressCache, evaluationQueue, evaluationConfig)
	datasetManager := ProvideDatasetUseCase(datasetRepository, datasetLoader)
	evaluationHandler := ProvideEvaluationHandler(service, datasetManager, progressCache, specRegistry)
	pythonGrpcConfig := ProvidePythonGrpcConfig()
	gateway := ProvideQualityGateway(pythonGrpcConfig)
	checkRecordRepository := ProvideQualityCheckRecordRepository(db)
	repository := ProvideDataSourceRepository(db)
	datasourceService := ProvideDataSourceService(repository, idGenerator)
	qualityService := ProvideQualityService(gateway, checkRecordRepository, idGenerator, pythonGrpcConfig, datasourceService)
	qualityHandler := ProvideQualityHandler(qualityService)
	dataSourceHandler := ProvideDataSourceHandler(datasourceService)
	semanticRepository := ProvideSemanticRepository(db)
	coverageReporter := ProvideSemanticCoverageReporter(db)
	semanticProfileReader := ProvideSemanticProfileReader(db)
	semanticService := ProvideSemanticModelService(semanticRepository, idGenerator, coverageReporter, semanticProfileReader)
	semanticHandler := ProvideSemanticHandler(semanticService)
	auditRepository := ProvideAuditRepository(db)
	auditHandler := ProvideAuditHandler(auditRepository)
	traceRepository := ProvideTraceRepository(db)
	traceHandler := ProvideTraceHandler(traceRepository)
	handler := ProvideWebHandler()
	authMiddleware := ProvideAuthMiddleware(accountService)
	tenantMiddleware := ProvideTenantMiddleware()
	writer := ProvideAuditWriter(auditRepository)
	auditMiddleware := ProvideAuditMiddleware(writer)
	router := ProvideRouter(authHandler, knowledgeBaseHandler, sessionHandler, messageHandler, chatHandler, tenantHandler, agentHandler, registryAgentHandler, graphHandler, modelHandler, taskHandler, ragOptimizerHandler, guardrailHandler, evaluationHandler, qualityHandler, dataSourceHandler, semanticHandler, auditHandler, traceHandler, handler, authMiddleware, tenantMiddleware, auditMiddleware)
	corsMiddleware := ProvideCORSMiddleware()
	recoveryMiddleware := ProvideRecoveryMiddleware()
	loggerMiddleware := ProvideLoggerMiddleware()
	traceMiddleware := ProvideTraceMiddleware()
	middlewares := ProvideMiddlewares(authMiddleware, tenantMiddleware, corsMiddleware, recoveryMiddleware, loggerMiddleware, traceMiddleware)
	evaluationWorker := ProvideEvaluationWorker(evaluationQueue, progressCache, llmChat, retriever, specRegistry, evaluationTaskRepository, evaluationResultRepository, datasetLoader, evaluationConfig, db, datasourceService)
	app := ProvideApp(router, middlewares, specRegistry, chatConfig, evaluationConfig, evaluationWorker, retriever, retrievalCapability, graphService, knowledgeBaseRepository, knowledgeBaseService, writer, datasourceService, agentHandler, embedder)
	return app, nil
}

// wire.go:

func ProvideJWTConfig() *config.JWTConfig {
	return config.LoadJWTConfig()
}

func ProvideChatConfig() *config.ChatConfig {
	return config.LoadChatConfig()
}

func ProvideEvaluationConfig() *config.EvaluationConfig {
	return config.LoadEvaluationConfig()
}

func ProvideRedisConfig() *config.RedisConfig {
	return config.LoadRedisConfig()
}

func ProvideEmbeddingConfig() *config.EmbeddingConfig {
	return config.LoadEmbeddingConfig()
}

func ProvideNeo4jConfig() *config.Neo4jConfig {
	return config.LoadNeo4jConfig()
}

func ProvideKnowledgeBaseRepository(db *gorm.DB) knowledge.KnowledgeBaseRepository {
	return mysql.NewKnowledgeBaseRepository(db, true)
}

func ProvideKnowledgeRepository(db *gorm.DB) knowledge.KnowledgeRepository {
	return mysql.NewKnowledgeRepository(db)
}

func ProvideChunkRepository(db *gorm.DB) knowledge.ChunkRepository {
	return mysql.NewChunkRepository(db)
}

func ProvideKnowledgeBaseSettingRepository(db *gorm.DB) knowledge.KnowledgeBaseSettingRepository {
	return mysql.NewKnowledgeBaseSettingRepository(db)
}

func ProvideRetrievalSettingRepository(db *gorm.DB) knowledge.RetrievalSettingRepository {
	return mysql.NewRetrievalSettingRepository(db)
}

func ProvideTagRepository(db *gorm.DB) knowledge.TagRepository {
	return mysql.NewTagRepository(db)
}

func ProvideSessionRepository(db *gorm.DB) conversation.SessionRepository {
	return mysql.NewSessionRepository(db)
}

func ProvideMessageRepository(db *gorm.DB) conversation.MessageRepository {
	return mysql.NewMessageRepository(db)
}

func ProvideUserRepository(db *gorm.DB) user.UserRepository {
	return mysql.NewUserRepository(db)
}

func ProvideRefreshTokenRepository(db *gorm.DB) user.RefreshTokenRepository {
	return mysql.NewRefreshTokenRepository(db)
}

func ProvideTenantRepository(db *gorm.DB) tenant.TenantRepository {
	return mysql.NewTenantRepository(db)
}

func ProvideTenantUserRepository(db *gorm.DB) tenant.TenantUserRepository {
	return mysql.NewTenantUserRepository(db)
}

func ProvideGraphRepository(db *gorm.DB) knowledge.GraphRepository {
	return mysql.NewGraphMetaRepository(db)
}

// ProvideGraphRepositoryWithFallback 返回可用的图谱仓储：优先使用 Neo4j，
// 当未配置 Neo4j（neo4jRepo 为 nil）时降级到基于 MySQL 的图谱存储，
// 从而保证 GraphService 在无 Neo4j 部署下依然可用。
func ProvideGraphRepositoryWithFallback(neo4jRepo knowledge.GraphRepository, db *gorm.DB) knowledge.GraphRepository {
	if neo4jRepo != nil {
		return neo4jRepo
	}
	return mysql.NewGraphMetaRepository(db)
}

func ProvideGraphQueryRepository(db *gorm.DB) knowledge.GraphQueryRepository {
	return mysql.NewGraphQueryRepository(db, true)
}

func ProvideSessionService(
	sessionRepo conversation.SessionRepository,
	messageRepo conversation.MessageRepository,
	retrievalSettingRepo knowledge.RetrievalSettingRepository,
) *chat.SessionService {
	return chat.NewSessionService(sessionRepo, messageRepo, retrievalSettingRepo)
}

func ProvideMessageService(messageRepo conversation.MessageRepository) *chat.MessageService {
	return chat.NewMessageService(messageRepo)
}

// ProvideLLMChatService 提供领域层的 LLMChatService 接口实现
func ProvideLLMChatService(chatConfig *config.ChatConfig) conversation.LLMChatService {
	if chatConfig == nil || chatConfig.APIKey == "" {
		return nil
	}

	chatConfigInfra := &chat2.ChatConfig{
		Source:    common.ModelSource(chatConfig.Provider),
		BaseURL:   chatConfig.BaseURL,
		ModelName: chatConfig.ModelName,
		APIKey:    chatConfig.APIKey,
		Provider:  chatConfig.Provider,
		ModelID:   fmt.Sprintf("chat_%d", 0),
	}
	chat3, err := chat2.NewChat(chatConfigInfra)
	if err != nil {
		return nil
	}

	return chat2.NewChatServiceAdapter(chat3)
}

func ProvideAccountService(
	userRepo user.UserRepository,
	refreshRepo user.RefreshTokenRepository,
	jwtConfig *config.JWTConfig,
	tenantRepo tenant.TenantRepository,
) *account.AccountService {
	return account.NewAccountService(userRepo, refreshRepo, jwtConfig, tenantRepo)
}

func ProvideKnowledgeBaseService(
	kbRepo knowledge.KnowledgeBaseRepository,
	kbSettingRepo knowledge.KnowledgeBaseSettingRepository,
	knowledgeRepo knowledge.KnowledgeRepository,
	chunkRepo knowledge.ChunkRepository,
	statsQuerier knowledge.KnowledgeStatsQuerier,
	vectorRepo knowledge.VectorRepository,
	graphRepo knowledge.GraphRepository,
) knowledge2.KnowledgeBaseService {
	return knowledge2.NewKnowledgeBaseService(kbRepo, kbSettingRepo, knowledgeRepo, chunkRepo, statsQuerier, vectorRepo, graphRepo)
}

// ProvideVectorRepository provides the vector repository
func ProvideVectorRepository(vectorRetriever *retriever.VectorRetriever) knowledge.VectorRepository {
	return retriever.NewVectorRepositoryAdapter(vectorRetriever)
}

func ProvideKnowledgeStatsQuerier(db *gorm.DB) knowledge.KnowledgeStatsQuerier {
	return mysql.NewKnowledgeStatsQuerier(db)
}

func ProvideKnowledgeService(
	knowledgeRepo knowledge.KnowledgeRepository,
	chunkRepo knowledge.ChunkRepository,
	kbSettingRepo knowledge.KnowledgeBaseSettingRepository,
	txManager knowledge.TransactionManager,
) knowledge2.KnowledgeService {
	return knowledge2.NewKnowledgeService(knowledgeRepo, chunkRepo, kbSettingRepo, txManager)
}

func ProvideTransactionManager(db *gorm.DB) knowledge.TransactionManager {
	return mysql.NewTransactionManager(db)
}

func ProvideModelService(modelRepo llm.ModelRepository, modelFactory llm.ModelFactory) *chat.ModelService {
	return chat.NewModelService(modelRepo, modelFactory)
}

func ProvideChatService(
	llmClient llm.ChatRepository,
	modelRepo llm.ModelRepository,
	modelFactory llm.ModelFactory,
) *chat.ChatService {
	return chat.NewChatService(llmClient, modelRepo, modelFactory)
}

// ProvideLLMClient provides the LLM client
func ProvideLLMClient(chatConfig *config.ChatConfig) llm.ChatRepository {
	if chatConfig == nil || chatConfig.APIKey == "" {
		return nil
	}
	modelConfig := &llm.ModelConfig{
		Provider:  llm.Provider(chatConfig.Provider),
		BaseURL:   chatConfig.BaseURL,
		ModelName: chatConfig.ModelName,
		APIKey:    chatConfig.APIKey,
	}
	client, err := llm2.NewChatRepository(modelConfig)
	if err != nil {
		return nil
	}
	return client
}

// ProvideModelRepository provides the model repository
func ProvideModelRepository(db *gorm.DB) llm.ModelRepository {
	return mysql.NewModelRepository(db)
}

// ProvideModelFactory provides the model factory
func ProvideModelFactory() llm.ModelFactory {
	return llm2.NewModelFactoryWithObservability()
}

// ProvideChatModel 基于聊天配置创建 model.ChatModel，
// 供 RAG 检索优化（HyDE/查询改写）与安全护栏使用。
// 未配置或创建失败时返回 nil，对应功能降级。
func ProvideChatModel(chatConfig *config.ChatConfig) model.ChatModel {
	if chatConfig == nil || chatConfig.APIKey == "" {
		return nil
	}
	chatModel, err := chat2.NewChatModel(context.Background(), &chat2.ChatConfig{
		Source:    common.ModelSource(chatConfig.Provider),
		BaseURL:   chatConfig.BaseURL,
		ModelName: chatConfig.ModelName,
		APIKey:    chatConfig.APIKey,
		Provider:  chatConfig.Provider,
		ModelID:   "chat_optimizer",
	})
	if err != nil {
		log.Printf("[ChatModel] 创建失败，RAG优化/护栏功能降级: %v", err)
		return nil
	}
	return chatModel
}

// ProvideNeo4jDriver provides the Neo4j driver
func ProvideNeo4jDriver(cfg *config.Neo4jConfig) (neo4j.DriverWithContext, error) {
	if cfg == nil || cfg.URI == "" {
		return nil, nil
	}
	return CreateDriver(context.Background(), Neo4jConfig{
		URI:      cfg.URI,
		Username: cfg.Username,
		Password: cfg.Password,
	})
}

// ProvideNeo4jGraphRepository provides the Neo4j graph repository
func ProvideNeo4jGraphRepository(driver neo4j.DriverWithContext, cfg *config.Neo4jConfig) (knowledge.GraphRepository, error) {
	if driver == nil {
		return nil, nil
	}
	dbName := "neo4j"
	if cfg != nil && cfg.DatabaseName != "" {
		dbName = cfg.DatabaseName
	}
	return neo4j2.NewNeo4jRepositoryFromDriver(driver, dbName)
}

// ProvideGraphService provides the Graph service with Neo4j repository
func ProvideGraphService(
	graphRepo knowledge.GraphRepository,
	graphQueryRepo knowledge.GraphQueryRepository,
	llmChat rag.LLMChat,
) *knowledge2.GraphService {
	if graphRepo == nil {
		return nil
	}

	return knowledge2.NewGraphServiceWithQuery(graphRepo, graphQueryRepo, graph.NewLLMExtractor(llmChat))
}

func ProvideEvaluationService(
	datasetService evaluation.DatasetService,
	taskRepo evaluation2.EvaluationTaskRepository,
	resultRepo evaluation2.EvaluationResultRepository,
	progressCache *cache.ProgressCache,
	evalQueue *cache.EvaluationQueue,
	evalConfig *config.EvaluationConfig,
) *evaluation.Service {

	pythonEndpoint := "http://localhost:18888"
	if evalConfig != nil && evalConfig.PythonEndpoint != "" {
		pythonEndpoint = evalConfig.PythonEndpoint
	}
	graderCatalog := evaluation.NewPythonEvaluationClient(pythonEndpoint)
	return evaluation.NewService(datasetService, taskRepo, resultRepo, progressCache, evalQueue, graderCatalog)
}

// ProvideDatasetLoader provides the dataset loader
func ProvideDatasetLoader(db *gorm.DB, datasetRepo evaluation2.DatasetRepository) *evaluation.DatasetLoader {
	return evaluation.NewDatasetLoader(db, datasetRepo)
}

// ProvideDatasetService provides the dataset service
func ProvideDatasetService(loader *evaluation.DatasetLoader) evaluation.DatasetService {
	return loader
}

// ProvideDocReaderClient 提供文档读取客户端
func ProvideDocReaderClient() (*docreader.Client, error) {

	return docreader.NewClient("localhost:50051")
}

// ProvideIDGenerator 提供唯一 ID 生成器
func ProvideIDGenerator() id.IDGenerator {
	return id.NewIDGenerator()
}

// ProvideDocumentProcessorService 提供文档处理服务（解析→分块→向量化→图谱提取）
func ProvideDocumentProcessorService(
	kbRepo knowledge.KnowledgeBaseRepository,
	knowledgeRepo knowledge.KnowledgeRepository,
	chunkRepo knowledge.ChunkRepository,
	vectorRepo knowledge.VectorRepository,
	graphRepo knowledge.GraphRepository,
	docReaderClient *docreader.Client,
	embedder embedding.Embedder,
	llmClient llm.ChatRepository,
	idGenerator id.IDGenerator,
) knowledge2.DocumentProcessorService {
	return knowledge2.NewDocumentProcessorService(
		kbRepo, knowledgeRepo, chunkRepo, vectorRepo, graphRepo,
		docReaderClient, embedder, llmClient, idGenerator,
	)
}

func ProvideAgentOrchestrator(registry *framework.SpecRegistry) agent.AgentExecutor {

	orchestrator := framework.NewRegistryAgentOrchestrator(registry.GetInstance)
	return orchestrator
}

func ProvideExecuteService(executor agent.AgentExecutor) *agent2.ExecuteService {
	return agent2.NewExecuteService(executor)
}

func ProvideResearchService(executor agent.AgentExecutor) *agent2.ResearchService {
	config2 := agent.DefaultDeepResearchConfig()
	return agent2.NewResearchService(executor, config2)
}

func ProvideProgressService() *agent2.ProgressService {
	return agent2.NewProgressService()
}

func ProvideConfigService() *agent2.ConfigService {
	return agent2.NewConfigService()
}

func ProvideAgentPersistenceService(
	sessionRepo conversation.SessionRepository,
	messageRepo conversation.MessageRepository,
) *agent2.AgentPersistenceService {
	return agent2.NewAgentPersistenceService(sessionRepo, messageRepo)
}

func ProvideAgentRegistry() *framework.SpecRegistry {
	return framework.NewSpecRegistry()
}

// ProvideRedisClient provides the Redis client.
// Redis 不可用时优雅降级（返回 nil），不阻断应用启动；
// 下游依赖（进度缓存、队列、任务队列、Worker）均能容忍 nil 客户端。
func ProvideRedisClient(cfg *config.RedisConfig) (*redis.Client, error) {
	if cfg == nil || cfg.Addr == "" {
		log.Printf("[Redis] 未配置地址，相关功能降级运行")
		return nil, nil
	}
	rc, err := redis2.NewClient(cfg)
	if err != nil {
		log.Printf("[Redis] 连接失败，相关功能降级运行: %v", err)
		return nil, nil
	}
	return rc.GetClient(), nil
}

func ProvideEvaluationProgressCache(redisClient *redis.Client) *cache.ProgressCache {
	return cache.NewProgressCache(redisClient)
}

func ProvideEvaluationQueue(redisClient *redis.Client) *cache.EvaluationQueue {
	return cache.NewQueue(redisClient, 100)
}

// ProvideEvaluationWorker 装配评测 Worker：
// 队列/进度缓存经领域端口注入，QA 评测执行器使用已装配的 LLMChat，
// 指标计算通过 Python 评测服务客户端完成。
func ProvideEvaluationWorker(
	evalQueue *cache.EvaluationQueue,
	progressCache *cache.ProgressCache,
	llmChat rag.LLMChat,
	retriever rag.Retriever,
	agentRegistry *framework.SpecRegistry,
	taskRepo evaluation2.EvaluationTaskRepository,
	resultRepo evaluation2.EvaluationResultRepository,
	datasetLoader *evaluation.DatasetLoader,
	evalConfig *config.EvaluationConfig,
	db *gorm.DB,
	datasourceProvider datasource.ConnectionProvider,
) *evaluation.EvaluationWorker {

	registry := executor.NewExecutorRegistry()
	if err := registry.Register(executor.NewQAExecutor(llmChat)); err != nil {
		log.Printf("[Worker] 注册 QA 执行器失败: %v", err)
	}
	if err := registry.Register(executor.NewRAGExecutor(retriever, llmChat)); err != nil {
		log.Printf("[Worker] 注册 RAG 执行器失败: %v", err)
	}
	agentService := evaluation.NewAgentServiceAdapter(agentRegistry)
	// Agent 单条评测超时来自配置（EVALUATION_AGENT_TIMEOUT，默认 180s）：一问含多轮工具调用，
	// 旧的硬编码 60s 会误杀对比/图表等复杂题（latency≈60000、llm_calls=0、空答案）。
	agentTimeout := 180 * time.Second
	if evalConfig != nil && evalConfig.AgentTimeout > 0 {
		agentTimeout = time.Duration(evalConfig.AgentTimeout) * time.Second
	}
	if err := registry.Register(executor.NewAgentExecutor(agentService, agentTimeout)); err != nil {
		log.Printf("[Worker] 注册 Agent 执行器失败: %v", err)
	}
	// Text2SQL 执行器：复用 Agent 适配器生成 SQL，另注入只读 SQLRunner（业务库 + 外部数据源），
	// 只读执行金标准/生成 SQL 供 Python 算执行准确率。与 Agent 共用单条超时。
	sqlRunner := evaluation.NewSQLRunner(db, datasourceProvider)
	if err := registry.Register(executor.NewText2SQLExecutor(agentService, sqlRunner, agentTimeout)); err != nil {
		log.Printf("[Worker] 注册 Text2SQL 执行器失败: %v", err)
	}

	pythonEndpoint := "http://localhost:18888"
	maxConcurrent := 3
	maxRetries := 3
	if evalConfig != nil {
		if evalConfig.PythonEndpoint != "" {
			pythonEndpoint = evalConfig.PythonEndpoint
		}
		if evalConfig.MaxConcurrent > 0 {
			maxConcurrent = evalConfig.MaxConcurrent
		}
		if evalConfig.MaxRetries > 0 {
			maxRetries = evalConfig.MaxRetries
		}
	}
	pythonClient := evaluation.NewPythonEvaluationClient(pythonEndpoint)

	workerConfig := &evaluation.WorkerConfig{
		MaxConcurrent: maxConcurrent,
		PollTimeout:   5 * time.Second,
		MaxRetries:    maxRetries,
	}

	return evaluation.NewWorker(
		evalQueue,
		progressCache,
		pythonClient,
		datasetLoader,
		registry,
		taskRepo,
		resultRepo,
		workerConfig,
	)
}

func ProvideDatasetUseCase(
	datasetRepo evaluation2.DatasetRepository,
	loader *evaluation.DatasetLoader,
) *evaluation.DatasetManager {
	return evaluation.NewDatasetManager(datasetRepo, loader)
}

func ProvideAuthMiddleware(accountService *account.AccountService) *middleware.AuthMiddleware {
	return middleware.NewAuthMiddleware(accountService)
}

func ProvideTenantMiddleware() *middleware.TenantMiddleware {
	return middleware.NewTenantMiddleware()
}

func ProvideCORSMiddleware() *middleware.CORSMiddleware {
	return middleware.NewCORSMiddleware()
}

func ProvideRecoveryMiddleware() *middleware.RecoveryMiddleware {
	return middleware.NewRecoveryMiddleware()
}

func ProvideLoggerMiddleware() *middleware.LoggerMiddleware {
	return middleware.NewLoggerMiddleware()
}

func ProvideTraceMiddleware() *middleware.TraceMiddleware {
	return middleware.NewTraceMiddleware()
}

func ProvideAuditMiddleware(writer *audit.Writer) *middleware.AuditMiddleware {
	return middleware.NewAuditMiddleware(writer)
}

func ProvideAuditRepository(db *gorm.DB) audit2.Repository {
	return mysql.NewAuditRepository(db)
}

// ProvideAuditWriter 提供审计异步批量写入器。
// 后台 flush goroutine 在构造时启动，App.Shutdown 负责优雅收尾。
func ProvideAuditWriter(repo audit2.Repository) *audit.Writer {
	return audit.NewWriter(repo, audit.DefaultWriterConfig())
}

func ProvideAuditHandler(repo audit2.Repository) *handler.AuditHandler {
	return handler.NewAuditHandler(repo)
}

func ProvideTraceRepository(db *gorm.DB) domaintrace.Repository {
	return mysql.NewTraceRepository(db)
}

func ProvideTraceHandler(repo domaintrace.Repository) *handler.TraceHandler {
	return handler.NewTraceHandler(repo)
}

func ProvideAuthHandler(accountService *account.AccountService) *handler.AuthHandler {
	return handler.NewAuthHandler(accountService)
}

func ProvideKnowledgeBaseHandler(
	kbService knowledge2.KnowledgeBaseService,
	documentProcessor knowledge2.DocumentProcessorService,
	retrieval *knowledge2.RetrievalCapability,
) *handler.KnowledgeBaseHandler {
	return handler.NewKnowledgeBaseHandler(kbService, documentProcessor, retrieval)
}

// ProvideRetrievalCapability 装配统一检索能力封装：Agent 路径与 REST /knowledge/search 共用。
// 重排器已接线但默认关闭（GovernedQuery.EnableRerank 缺省 false），按需可插拔开启。
func ProvideRetrievalCapability(retriever rag.Retriever) *knowledge2.RetrievalCapability {
	return knowledge2.NewRetrievalCapability(retriever, rag2.NewReranker())
}

func ProvideSessionHandler(
	sessionService *chat.SessionService,
	chatService *chat.ChatService,
) *handler.SessionHandler {
	return handler.NewSessionHandler(sessionService, chatService)
}

func ProvideMessageHandler(messageService *chat.MessageService) *handler.MessageHandler {
	return handler.NewMessageHandler(messageService)
}

func ProvideChatHandler(chatService *chat.ChatService) *handler.ChatHandler {
	return handler.NewChatHandler(chatService)
}

func ProvideTenantHandler(accountService *account.AccountService) *handler.TenantHandler {
	return handler.NewTenantHandler(accountService)
}

func ProvideAgentHandler(
	executeUC *agent2.ExecuteService,
	researchUC *agent2.ResearchService,
	configUC *agent2.ConfigService,
	progressUC *agent2.ProgressService,
	persistenceSvc *agent2.AgentPersistenceService,
	retrievalSettingRepo knowledge.RetrievalSettingRepository,
) *handler.AgentHandler {
	return handler.NewAgentHandler(executeUC, researchUC, configUC, progressUC, persistenceSvc, retrievalSettingRepo)
}

func ProvideEvaluationHandler(
	evalService *evaluation.Service,
	datasetManager *evaluation.DatasetManager,
	progressCache *cache.ProgressCache,
	agentRegistry *framework.SpecRegistry,
) *handler.EvaluationHandler {
	return handler.NewEvaluationHandler(evalService, datasetManager, progressCache, agentRegistry)
}

func ProvideGraphHandler(graphService *knowledge2.GraphService) *handler.GraphHandler {
	return handler.NewGraphHandler(graphService)
}

func ProvideModelHandler(
	modelService *chat.ModelService,
	chatService *chat.ChatService,
) *handler.ModelHandler {
	return handler.NewModelHandler(modelService, chatService)
}

func ProvideRegistryAgentHandler(registry *framework.SpecRegistry) *handler.RegistryAgentHandler {
	return handler.NewRegistryAgentHandler(registry)
}

func ProvideTaskHandler(taskService *evaluation.TaskService) *handler.TaskHandler {
	return handler.NewTaskHandler(taskService)
}

// ProvideRAGOptimizerHandler 装配 RAG 检索优化器。
// 未配置 ChatModel 时降级（handler 内部判空跳过优化）。
func ProvideRAGOptimizerHandler(chatModel model.ChatModel, baseRetriever rag.Retriever) *handler.RAGOptimizerHandler {
	if chatModel == nil {
		return handler.NewRAGOptimizerHandler(nil)
	}
	optimizer := knowledge2.NewOptimizer(chatModel, baseRetriever)
	return handler.NewRAGOptimizerHandler(optimizer)
}

// ProvideGuardrailHandler 装配内容安全护栏。
// 未配置 ChatModel 时降级（handler 内部判空放行）。
func ProvideGuardrailHandler(chatModel model.ChatModel) *handler.GuardrailHandler {
	if chatModel == nil {
		return handler.NewGuardrailHandler(nil)
	}
	svc := tools.NewGuardrailService(chatModel)
	impl, ok := svc.(*tools.GuardrailServiceImpl)
	if !ok {
		return handler.NewGuardrailHandler(nil)
	}
	return handler.NewGuardrailHandler(impl)
}

func ProvideWebHandler() *web.Handler {

	return web.NewHandler("./static")
}

func ProvideEvaluationTaskRepository(db *gorm.DB) evaluation2.EvaluationTaskRepository {
	return mysql.NewEvaluationTaskRepository(db)
}

func ProvideTaskService(
	taskRepo task.TaskRepository,
	taskQueue task.TaskQueue,
) *evaluation.TaskService {
	return evaluation.NewTaskService(taskRepo, taskQueue)
}

func ProvideTaskRepository(db *gorm.DB) task.TaskRepository {
	return mysql.NewTaskRepository(db)
}

// ProvideTaskQueue 提供基于 Redis 的任务队列。
// Redis 不可用时返回 nil（任务调度功能降级，不阻断启动）。
func ProvideTaskQueue(redisClient *redis.Client) task.TaskQueue {
	if redisClient == nil {
		return nil
	}
	return queue.NewRedisTaskQueue(redisClient)
}

func ProvideEvaluationResultRepository(db *gorm.DB) evaluation2.EvaluationResultRepository {
	return mysql.NewEvaluationResultRepository(db)
}

func ProvideDatasetRepository(db *gorm.DB) evaluation2.DatasetRepository {
	return mysql.NewDatasetRepository(db)
}

func ProvideChatRepository(chatConfig *config.ChatConfig) (llm.ChatRepository, error) {

	if chatConfig.APIKey != "" {
		modelConfig := &llm.ModelConfig{
			Provider:  llm.Provider(chatConfig.Provider),
			BaseURL:   chatConfig.BaseURL,
			ModelName: chatConfig.ModelName,
			APIKey:    chatConfig.APIKey,
		}
		return llm2.NewChatRepository(modelConfig)
	}

	return nil, nil
}

func ProvideEmbedder(cfg *config.EmbeddingConfig) (embedding.Embedder, error) {
	return embedding2.NewEmbedder(cfg)
}

func ProvideVectorRetriever(embedder embedding.Embedder) (*retriever.VectorRetriever, error) {
	return retriever.NewVectorRetriever(embedder)
}

func ProvideMilvusRetriever() rag2.MilvusRetriever {

	vectorRetriever, err := retriever.NewVectorRetriever(nil)
	if err != nil {

		return nil
	}

	return retriever.NewMilvusAdapter(vectorRetriever)
}

func ProvideRAGGraphRepository() rag.GraphRepository {

	return nil
}

func ProvideRetriever(
	kbSettingRepo knowledge.KnowledgeBaseSettingRepository,
	chunkRepo knowledge.ChunkRepository,
	embedder embedding.Embedder,
	milvusRetriever rag2.MilvusRetriever,
	graphRepo rag.GraphRepository,
	graphQueryRepo knowledge.GraphQueryRepository,
) rag.Retriever {

	return rag2.NewRetriever(kbSettingRepo, chunkRepo, embedder, milvusRetriever, graphRepo, nil, rag2.NewReranker())
}

func ProvideReranker() rag.Reranker {
	return rag2.NewReranker()
}

func ProvideRAGLLMChat(chatRepo llm.ChatRepository) rag.LLMChat {
	if chatRepo != nil {
		return rag2.NewLLMChatAdapterWithRepo(chatRepo)
	}
	return rag2.NewLLMChatAdapter(nil)
}

func ProvideRAGService(retriever2 rag.Retriever,

	reranker rag.Reranker,
	queryStrengthener rag.QueryStrengthener,
	graphRepo knowledge.GraphRepository,
	graphQueryRepo knowledge.GraphQueryRepository,
	llmChat rag.LLMChat,
) *knowledge2.RAGService {
	return knowledge2.NewRAGService(retriever2, reranker, queryStrengthener, graphRepo, graphQueryRepo, llmChat, graph.NewLLMExtractor(llmChat))
}

func ProvideRouter(
	authHandler *handler.AuthHandler,
	knowledgeBaseHandler *handler.KnowledgeBaseHandler,
	sessionHandler *handler.SessionHandler,
	messageHandler *handler.MessageHandler,
	chatHandler *handler.ChatHandler,
	tenantHandler *handler.TenantHandler,
	agentHandler *handler.AgentHandler,
	registryAgentHandler *handler.RegistryAgentHandler,
	graphHandler *handler.GraphHandler,
	modelHandler *handler.ModelHandler,
	taskHandler *handler.TaskHandler,
	ragOptimizerHandler *handler.RAGOptimizerHandler,
	guardrailHandler *handler.GuardrailHandler,
	evaluationHandler *handler.EvaluationHandler,
	qualityHandler *handler.QualityHandler,
	dataSourceHandler *handler.DataSourceHandler,
	semanticHandler *handler.SemanticHandler,
	auditHandler *handler.AuditHandler,
	traceHandler *handler.TraceHandler,
	webHandler *web.Handler,
	authMiddleware *middleware.AuthMiddleware,
	tenantMiddleware *middleware.TenantMiddleware,
	auditMiddleware *middleware.AuditMiddleware,
) *router.Router {
	return router.NewRouter(
		authHandler,
		knowledgeBaseHandler,
		sessionHandler,
		messageHandler,
		chatHandler,
		tenantHandler,
		agentHandler,
		registryAgentHandler,
		graphHandler,
		modelHandler,
		taskHandler,
		ragOptimizerHandler,
		guardrailHandler,
		evaluationHandler,
		qualityHandler,
		dataSourceHandler,
		semanticHandler,
		auditHandler,
		traceHandler,
		webHandler,
		authMiddleware,
		tenantMiddleware,
		auditMiddleware,
	)
}

// ProvidePythonGrpcConfig 提供 Python gRPC 配置。
func ProvidePythonGrpcConfig() *config.PythonGrpcConfig {
	return config.LoadPythonGrpcConfig()
}

// ProvideQualityGateway 提供数据质量 gRPC 网关（Python 服务适配器）。
func ProvideQualityGateway(cfg *config.PythonGrpcConfig) quality.Gateway {
	target := "localhost:50051"
	timeout := 60 * time.Second
	if cfg != nil {
		if cfg.Target != "" {
			target = cfg.Target
		}
		if cfg.Timeout > 0 {
			timeout = time.Duration(cfg.Timeout) * time.Second
		}
	}
	return quality2.NewGateway(target, timeout)
}

// ProvideQualityCheckRecordRepository 提供质检记录仓储。
func ProvideQualityCheckRecordRepository(db *gorm.DB) quality3.CheckRecordRepository {
	return mysql.NewQualityCheckRecordRepository(db)
}

// ProvideQualityService 提供数据质量应用服务。
// 注入数据源服务作为 Sampler：数据源直评时由 Go 抽样取数推给 Python。
func ProvideQualityService(gateway quality.Gateway, repo quality3.CheckRecordRepository, idGen id.IDGenerator, cfg *config.PythonGrpcConfig, sampler *datasource2.Service) *quality.Service {
	timeout := 60 * time.Second
	if cfg != nil && cfg.Timeout > 0 {
		timeout = time.Duration(cfg.Timeout) * time.Second
	}
	return quality.NewService(gateway, timeout, repo, idGen, sampler)
}

// ProvideQualityHandler 提供数据质量 HTTP 处理器。
func ProvideQualityHandler(service *quality.Service) *handler.QualityHandler {
	return handler.NewQualityHandler(service)
}

// ProvideDataSourceRepository 提供数据源仓储。
func ProvideDataSourceRepository(db *gorm.DB) datasource.Repository {
	return mysql.NewDataSourceRepository(db)
}

// ProvideDataSourceService 提供数据源应用服务（含凭证加密与受管连接池）。
// DATASOURCE_SECRET_KEY 未配置时 fail-fast：不允许明文/无密钥启动。
func ProvideDataSourceService(repo datasource.Repository, idGen id.IDGenerator) *datasource2.Service {
	cipher, err := datasource2.NewCipherFromEnv()
	if err != nil {
		panic(fmt.Sprintf("外部数据源加密初始化失败: %v（请配置 %s）", err, datasource2.SecretKeyEnv))
	}
	cm := datasource2.NewConnectionManager(repo, cipher, datasource2.DefaultPoolOptions())
	return datasource2.NewService(repo, cipher, cm, idGen)
}

// ProvideDataSourceHandler 提供数据源 HTTP 处理器。
func ProvideDataSourceHandler(service *datasource2.Service) *handler.DataSourceHandler {
	return handler.NewDataSourceHandler(service)
}

// ProvideSemanticRepository 提供指标语义层模型仓储。
func ProvideSemanticRepository(db *gorm.DB) semantic.Repository {
	return mysql.NewSemanticRepository(db)
}

// ProvideSemanticCoverageReporter 提供语义查询覆盖率读侧（治理命中率聚合）。
func ProvideSemanticCoverageReporter(db *gorm.DB) semantic.CoverageReporter {
	return mysql.NewSemanticCoverageRepository(db)
}

// ProvideSemanticProfileReader 提供语义层值映射诊断所需的列画像读侧（复用列画像仓储）。
func ProvideSemanticProfileReader(db *gorm.DB) semantic2.ProfileReader {
	return mysql.NewColumnProfileRepository(db)
}

// ProvideSemanticModelService 提供语义模型建模应用服务（受治理查询的写入口）。
func ProvideSemanticModelService(repo semantic.Repository, idGen id.IDGenerator, coverage semantic.CoverageReporter, profiles semantic2.ProfileReader) *semantic2.Service {
	return semantic2.NewService(repo, idGen, coverage, profiles)
}

// ProvideSemanticHandler 提供语义模型建模 HTTP 处理器。
func ProvideSemanticHandler(service *semantic2.Service) *handler.SemanticHandler {
	return handler.NewSemanticHandler(service)
}

// Middlewares 中间件集合
type Middlewares struct {
	Auth     *middleware.AuthMiddleware
	Tenant   *middleware.TenantMiddleware
	CORS     *middleware.CORSMiddleware
	Recovery *middleware.RecoveryMiddleware
	Logger   *middleware.LoggerMiddleware
	Trace    *middleware.TraceMiddleware
}

func ProvideMiddlewares(
	auth *middleware.AuthMiddleware, tenant2 *middleware.TenantMiddleware,
	cors *middleware.CORSMiddleware,
	recovery *middleware.RecoveryMiddleware,
	logger *middleware.LoggerMiddleware,
	trace *middleware.TraceMiddleware,
) *Middlewares {
	return &Middlewares{
		Auth:     auth,
		Tenant:   tenant2,
		CORS:     cors,
		Recovery: recovery,
		Logger:   logger,
		Trace:    trace,
	}
}

// App 应用程序实例
type App struct {
	Router           *router.Router
	Middlewares      *Middlewares
	AgentRegistry    *framework.SpecRegistry
	ChatConfig       *config.ChatConfig
	EvaluationConfig *config.EvaluationConfig
	EvaluationWorker *evaluation.EvaluationWorker
	// 以下依赖暴露给组合根（main.go），用于把 Agent 工具（rag_query/graph_query/kb_list）
	// 接线到真实检索/图谱/知识库服务，替代此前工具层的 mock/未接线状态。
	Retriever rag.Retriever
	// RetrievalCapability 是知识检索的唯一能力封装（多库检索+去重+截断+出处+阈值+可插拔重排）。
	// Agent 适配器（rag_query）与 REST /knowledge/search 共用同一封装，检索本体不再两路割裂。
	RetrievalCapability     *knowledge2.RetrievalCapability
	GraphService            *knowledge2.GraphService
	KnowledgeBaseRepository knowledge.KnowledgeBaseRepository
	// KnowledgeBaseService 暴露给组合根：文档写入/删除后经 SetCacheInvalidator 接线 RAG 硬缓存按库失效。
	KnowledgeBaseService knowledge2.KnowledgeBaseService
	// AuditWriter 暴露给组合根：优雅关闭时 flush 积压审计。
	AuditWriter *audit.Writer
	// DataSourceService 暴露给组合根：把查询类工具的 database_id 路由
	// 接线到外部数据源 ConnectionManager（InitDatasourceTools）。
	DataSourceService *datasource2.Service
	// AgentHandler 暴露给组合根：构造 ToolRegistry 后经 SetToolGateway 注入工具网关
	// （confirm-resume / UI 取数 / schema 查询），替代 tools 包级默认槽位。
	AgentHandler *handler.AgentHandler
	// Embedder 暴露给组合根：供 Agent 自我进化向量化任务/教训（experience 后台 worker 沉淀），
	// 由初始化器下发给 data_agent 预设。（内联反思记忆路径已下线，改由 experience worker 承担。）
	Embedder embedding.Embedder
}

func ProvideApp(
	r *router.Router,
	m *Middlewares,
	agentRegistry *framework.SpecRegistry,
	chatConfig *config.ChatConfig,
	evalConfig *config.EvaluationConfig,
	evalWorker *evaluation.EvaluationWorker, retriever2 rag.Retriever,

	retrievalCapability *knowledge2.RetrievalCapability,
	graphService *knowledge2.GraphService,
	kbRepo knowledge.KnowledgeBaseRepository,
	kbService knowledge2.KnowledgeBaseService,
	auditWriter *audit.Writer,
	dataSourceService *datasource2.Service,
	agentHandler *handler.AgentHandler,
	embedder embedding.Embedder,
) *App {
	return &App{
		Router:                  r,
		Middlewares:             m,
		AgentRegistry:           agentRegistry,
		ChatConfig:              chatConfig,
		EvaluationConfig:        evalConfig,
		EvaluationWorker:        evalWorker,
		Retriever:               retriever2,
		RetrievalCapability:     retrievalCapability,
		GraphService:            graphService,
		KnowledgeBaseRepository: kbRepo,
		KnowledgeBaseService:    kbService,
		AuditWriter:             auditWriter,
		DataSourceService:       dataSourceService,
		AgentHandler:            agentHandler,
		Embedder:                embedder,
	}
}

// Shutdown 关闭应用程序：flush 审计写入器，确保积压审计落库不丢。
func (a *App) Shutdown(ctx context.Context) error {
	if a.AuditWriter != nil {
		return a.AuditWriter.Close(ctx)
	}
	return nil
}
