# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import analytics_pb2 as proto_dot_analytics__pb2


class AnalyticsServiceStub(object):
    """数据分析服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeMetrics = channel.unary_unary(
                '/analytics.AnalyticsService/ComputeMetrics',
                request_serializer=proto_dot_analytics__pb2.MetricsRequest.SerializeToString,
                response_deserializer=proto_dot_analytics__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.AnalyzeTrend = channel.unary_unary(
                '/analytics.AnalyticsService/AnalyzeTrend',
                request_serializer=proto_dot_analytics__pb2.TrendRequest.SerializeToString,
                response_deserializer=proto_dot_analytics__pb2.TrendResponse.FromString,
                _registered_method=True)
        self.DiscoverInsights = channel.unary_unary(
                '/analytics.AnalyticsService/DiscoverInsights',
                request_serializer=proto_dot_analytics__pb2.InsightRequest.SerializeToString,
                response_deserializer=proto_dot_analytics__pb2.InsightResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer(object):
    """数据分析服务
    """

    def ComputeMetrics(self, request, context):
        """===== 统计计算 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeTrend(self, request, context):
        """===== 趋势分析 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverInsights(self, request, context):
        """===== 洞察发现 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeMetrics,
                    request_deserializer=proto_dot_analytics__pb2.MetricsRequest.FromString,
                    response_serializer=proto_dot_analytics__pb2.MetricsResponse.SerializeToString,
            ),
            'AnalyzeTrend': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeTrend,
                    request_deserializer=proto_dot_analytics__pb2.TrendRequest.FromString,
                    response_serializer=proto_dot_analytics__pb2.TrendResponse.SerializeToString,
            ),
            'DiscoverInsights': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverInsights,
                    request_deserializer=proto_dot_analytics__pb2.InsightRequest.FromString,
                    response_serializer=proto_dot_analytics__pb2.InsightResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """数据分析服务
    """

    @staticmethod
    def ComputeMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/ComputeMetrics',
            proto_dot_analytics__pb2.MetricsRequest.SerializeToString,
            proto_dot_analytics__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeTrend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/AnalyzeTrend',
            proto_dot_analytics__pb2.TrendRequest.SerializeToString,
            proto_dot_analytics__pb2.TrendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverInsights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/DiscoverInsights',
            proto_dot_analytics__pb2.InsightRequest.SerializeToString,
            proto_dot_analytics__pb2.InsightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
