# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/common.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/common.proto\x12\x06\x63ommon*\xb5\x03\n\tErrorCode\x12\x1a\n\x16\x45RROR_CODE_UNSPECIFIED\x10\x00\x12\x11\n\rERROR_CODE_OK\x10\x01\x12\x17\n\x13\x45RROR_CODE_INTERNAL\x10\x02\x12\x1f\n\x1b\x45RROR_CODE_INVALID_ARGUMENT\x10\x03\x12\x18\n\x14\x45RROR_CODE_NOT_FOUND\x10\x04\x12\x1e\n\x1a\x45RROR_CODE_UNAUTHENTICATED\x10\x05\x12 \n\x1c\x45RROR_CODE_PERMISSION_DENIED\x10\x06\x12 \n\x1c\x45RROR_CODE_DEADLINE_EXCEEDED\x10\x07\x12\x1a\n\x16\x45RROR_CODE_UNAVAILABLE\x10\x08\x12!\n\x1d\x45RROR_CODE_RESOURCE_EXHAUSTED\x10\t\x12 \n\x1c\x45RROR_CODE_DATASET_NOT_FOUND\x10\x64\x12 \n\x1c\x45RROR_CODE_MODEL_UNAVAILABLE\x10\x65\x12\x1d\n\x19\x45RROR_CODE_COMPUTE_FAILED\x10\x66\x12\x1f\n\x1b\x45RROR_CODE_UPSTREAM_TIMEOUT\x10gB\x17Z\x15link/api/proto/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025link/api/proto/common'
  _globals['_ERRORCODE']._serialized_start=31
  _globals['_ERRORCODE']._serialized_end=468
# @@protoc_insertion_point(module_scope)
