# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import docreader_pb2 as proto_dot_docreader__pb2


class DocumentReaderServiceStub(object):
    """文档解析服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseDocument = channel.unary_unary(
                '/docreader.DocumentReaderService/ParseDocument',
                request_serializer=proto_dot_docreader__pb2.ParseRequest.SerializeToString,
                response_deserializer=proto_dot_docreader__pb2.ParseResponse.FromString,
                _registered_method=True)
        self.ParseBatch = channel.unary_unary(
                '/docreader.DocumentReaderService/ParseBatch',
                request_serializer=proto_dot_docreader__pb2.ParseBatchRequest.SerializeToString,
                response_deserializer=proto_dot_docreader__pb2.ParseBatchResponse.FromString,
                _registered_method=True)
        self.OCRImage = channel.unary_unary(
                '/docreader.DocumentReaderService/OCRImage',
                request_serializer=proto_dot_docreader__pb2.OCRRequest.SerializeToString,
                response_deserializer=proto_dot_docreader__pb2.OCRResponse.FromString,
                _registered_method=True)
        self.OCRBatch = channel.unary_stream(
                '/docreader.DocumentReaderService/OCRBatch',
                request_serializer=proto_dot_docreader__pb2.OCRBatchRequest.SerializeToString,
                response_deserializer=proto_dot_docreader__pb2.OCRBatchResponse.FromString,
                _registered_method=True)
        self.ChunkDocument = channel.unary_unary(
                '/docreader.DocumentReaderService/ChunkDocument',
                request_serializer=proto_dot_docreader__pb2.ChunkRequest.SerializeToString,
                response_deserializer=proto_dot_docreader__pb2.ChunkResponse.FromString,
                _registered_method=True)
        self.FetchURL = channel.unary_unary(
                '/docreader.DocumentReaderService/FetchURL',
                request_serializer=proto_dot_docreader__pb2.FetchURLRequest.SerializeToString,
                response_deserializer=proto_dot_docreader__pb2.FetchURLResponse.FromString,
                _registered_method=True)


class DocumentReaderServiceServicer(object):
    """文档解析服务
    """

    def ParseDocument(self, request, context):
        """===== 文档解析 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OCRImage(self, request, context):
        """===== OCR 识别 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OCRBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChunkDocument(self, request, context):
        """===== 文档分块 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchURL(self, request, context):
        """===== URL 内容获取 =====
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentReaderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseDocument,
                    request_deserializer=proto_dot_docreader__pb2.ParseRequest.FromString,
                    response_serializer=proto_dot_docreader__pb2.ParseResponse.SerializeToString,
            ),
            'ParseBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseBatch,
                    request_deserializer=proto_dot_docreader__pb2.ParseBatchRequest.FromString,
                    response_serializer=proto_dot_docreader__pb2.ParseBatchResponse.SerializeToString,
            ),
            'OCRImage': grpc.unary_unary_rpc_method_handler(
                    servicer.OCRImage,
                    request_deserializer=proto_dot_docreader__pb2.OCRRequest.FromString,
                    response_serializer=proto_dot_docreader__pb2.OCRResponse.SerializeToString,
            ),
            'OCRBatch': grpc.unary_stream_rpc_method_handler(
                    servicer.OCRBatch,
                    request_deserializer=proto_dot_docreader__pb2.OCRBatchRequest.FromString,
                    response_serializer=proto_dot_docreader__pb2.OCRBatchResponse.SerializeToString,
            ),
            'ChunkDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ChunkDocument,
                    request_deserializer=proto_dot_docreader__pb2.ChunkRequest.FromString,
                    response_serializer=proto_dot_docreader__pb2.ChunkResponse.SerializeToString,
            ),
            'FetchURL': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchURL,
                    request_deserializer=proto_dot_docreader__pb2.FetchURLRequest.FromString,
                    response_serializer=proto_dot_docreader__pb2.FetchURLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'docreader.DocumentReaderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('docreader.DocumentReaderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentReaderService(object):
    """文档解析服务
    """

    @staticmethod
    def ParseDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/docreader.DocumentReaderService/ParseDocument',
            proto_dot_docreader__pb2.ParseRequest.SerializeToString,
            proto_dot_docreader__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/docreader.DocumentReaderService/ParseBatch',
            proto_dot_docreader__pb2.ParseBatchRequest.SerializeToString,
            proto_dot_docreader__pb2.ParseBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OCRImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/docreader.DocumentReaderService/OCRImage',
            proto_dot_docreader__pb2.OCRRequest.SerializeToString,
            proto_dot_docreader__pb2.OCRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OCRBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/docreader.DocumentReaderService/OCRBatch',
            proto_dot_docreader__pb2.OCRBatchRequest.SerializeToString,
            proto_dot_docreader__pb2.OCRBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChunkDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/docreader.DocumentReaderService/ChunkDocument',
            proto_dot_docreader__pb2.ChunkRequest.SerializeToString,
            proto_dot_docreader__pb2.ChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/docreader.DocumentReaderService/FetchURL',
            proto_dot_docreader__pb2.FetchURLRequest.SerializeToString,
            proto_dot_docreader__pb2.FetchURLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
