# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import judge_pb2 as proto_dot_judge__pb2


class JudgeServiceStub(object):
    """LLM 评测服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportProgress = channel.stream_unary(
                '/judge.JudgeService/ReportProgress',
                request_serializer=proto_dot_judge__pb2.ProgressUpdate.SerializeToString,
                response_deserializer=proto_dot_judge__pb2.ProgressResponse.FromString,
                _registered_method=True)
        self.SubmitResult = channel.unary_unary(
                '/judge.JudgeService/SubmitResult',
                request_serializer=proto_dot_judge__pb2.EvaluationResult.SerializeToString,
                response_deserializer=proto_dot_judge__pb2.ResultResponse.FromString,
                _registered_method=True)
        self.ListDatasets = channel.unary_unary(
                '/judge.JudgeService/ListDatasets',
                request_serializer=proto_dot_judge__pb2.ListDatasetsRequest.SerializeToString,
                response_deserializer=proto_dot_judge__pb2.ListDatasetsResponse.FromString,
                _registered_method=True)
        self.GetDataset = channel.unary_unary(
                '/judge.JudgeService/GetDataset',
                request_serializer=proto_dot_judge__pb2.GetDatasetRequest.SerializeToString,
                response_deserializer=proto_dot_judge__pb2.DatasetInfo.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/judge.JudgeService/HealthCheck',
                request_serializer=proto_dot_judge__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_judge__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class JudgeServiceServicer(object):
    """LLM 评测服务
    """

    def ReportProgress(self, request_iterator, context):
        """上报评测进度（单向流）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResult(self, request, context):
        """提交评测结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasets(self, request, context):
        """获取可用数据集列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataset(self, request, context):
        """获取数据集详情
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JudgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportProgress': grpc.stream_unary_rpc_method_handler(
                    servicer.ReportProgress,
                    request_deserializer=proto_dot_judge__pb2.ProgressUpdate.FromString,
                    response_serializer=proto_dot_judge__pb2.ProgressResponse.SerializeToString,
            ),
            'SubmitResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitResult,
                    request_deserializer=proto_dot_judge__pb2.EvaluationResult.FromString,
                    response_serializer=proto_dot_judge__pb2.ResultResponse.SerializeToString,
            ),
            'ListDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=proto_dot_judge__pb2.ListDatasetsRequest.FromString,
                    response_serializer=proto_dot_judge__pb2.ListDatasetsResponse.SerializeToString,
            ),
            'GetDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataset,
                    request_deserializer=proto_dot_judge__pb2.GetDatasetRequest.FromString,
                    response_serializer=proto_dot_judge__pb2.DatasetInfo.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_judge__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_judge__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'judge.JudgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('judge.JudgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JudgeService(object):
    """LLM 评测服务
    """

    @staticmethod
    def ReportProgress(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/judge.JudgeService/ReportProgress',
            proto_dot_judge__pb2.ProgressUpdate.SerializeToString,
            proto_dot_judge__pb2.ProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/judge.JudgeService/SubmitResult',
            proto_dot_judge__pb2.EvaluationResult.SerializeToString,
            proto_dot_judge__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/judge.JudgeService/ListDatasets',
            proto_dot_judge__pb2.ListDatasetsRequest.SerializeToString,
            proto_dot_judge__pb2.ListDatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/judge.JudgeService/GetDataset',
            proto_dot_judge__pb2.GetDatasetRequest.SerializeToString,
            proto_dot_judge__pb2.DatasetInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/judge.JudgeService/HealthCheck',
            proto_dot_judge__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_judge__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
