# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import quality_pb2 as proto_dot_quality__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/quality_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QualityServiceStub(object):
    """质量服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateQuality = channel.unary_unary(
                '/quality.QualityService/EvaluateQuality',
                request_serializer=proto_dot_quality__pb2.EvaluateQualityRequest.SerializeToString,
                response_deserializer=proto_dot_quality__pb2.EvaluateQualityResponse.FromString,
                _registered_method=True)
        self.EvaluateUnstructuredQuality = channel.unary_unary(
                '/quality.QualityService/EvaluateUnstructuredQuality',
                request_serializer=proto_dot_quality__pb2.EvaluateUnstructuredQualityRequest.SerializeToString,
                response_deserializer=proto_dot_quality__pb2.EvaluateUnstructuredQualityResponse.FromString,
                _registered_method=True)
        self.CleanData = channel.unary_unary(
                '/quality.QualityService/CleanData',
                request_serializer=proto_dot_quality__pb2.CleanDataRequest.SerializeToString,
                response_deserializer=proto_dot_quality__pb2.CleanDataResponse.FromString,
                _registered_method=True)
        self.ProcessPipeline = channel.unary_unary(
                '/quality.QualityService/ProcessPipeline',
                request_serializer=proto_dot_quality__pb2.ProcessPipelineRequest.SerializeToString,
                response_deserializer=proto_dot_quality__pb2.ProcessPipelineResponse.FromString,
                _registered_method=True)
        self.DetectDrift = channel.unary_unary(
                '/quality.QualityService/DetectDrift',
                request_serializer=proto_dot_quality__pb2.DetectDriftRequest.SerializeToString,
                response_deserializer=proto_dot_quality__pb2.DetectDriftResponse.FromString,
                _registered_method=True)
        self.ListDimensions = channel.unary_unary(
                '/quality.QualityService/ListDimensions',
                request_serializer=proto_dot_quality__pb2.ListDimensionsRequest.SerializeToString,
                response_deserializer=proto_dot_quality__pb2.ListDimensionsResponse.FromString,
                _registered_method=True)
        self.GetQualityRules = channel.unary_unary(
                '/quality.QualityService/GetQualityRules',
                request_serializer=proto_dot_quality__pb2.GetQualityRulesRequest.SerializeToString,
                response_deserializer=proto_dot_quality__pb2.GetQualityRulesResponse.FromString,
                _registered_method=True)
        self.UpdateQualityRules = channel.unary_unary(
                '/quality.QualityService/UpdateQualityRules',
                request_serializer=proto_dot_quality__pb2.UpdateQualityRulesRequest.SerializeToString,
                response_deserializer=proto_dot_quality__pb2.UpdateQualityRulesResponse.FromString,
                _registered_method=True)
        self.RegisterCustomEvaluator = channel.unary_unary(
                '/quality.QualityService/RegisterCustomEvaluator',
                request_serializer=proto_dot_quality__pb2.RegisterCustomEvaluatorRequest.SerializeToString,
                response_deserializer=proto_dot_quality__pb2.RegisterCustomEvaluatorResponse.FromString,
                _registered_method=True)
        self.RegisterCustomCleaner = channel.unary_unary(
                '/quality.QualityService/RegisterCustomCleaner',
                request_serializer=proto_dot_quality__pb2.RegisterCustomCleanerRequest.SerializeToString,
                response_deserializer=proto_dot_quality__pb2.RegisterCustomCleanerResponse.FromString,
                _registered_method=True)


class QualityServiceServicer(object):
    """质量服务
    """

    def EvaluateQuality(self, request, context):
        """评估结构化数据质量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateUnstructuredQuality(self, request, context):
        """评估非结构化数据质量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanData(self, request, context):
        """清洗数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPipeline(self, request, context):
        """执行端到端流程
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectDrift(self, request, context):
        """检测数据漂移
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDimensions(self, request, context):
        """列出可用的评估维度
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQualityRules(self, request, context):
        """获取质量规则
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateQualityRules(self, request, context):
        """更新质量规则
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterCustomEvaluator(self, request, context):
        """注册自定义评估器
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterCustomCleaner(self, request, context):
        """注册自定义清洗器
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QualityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateQuality': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateQuality,
                    request_deserializer=proto_dot_quality__pb2.EvaluateQualityRequest.FromString,
                    response_serializer=proto_dot_quality__pb2.EvaluateQualityResponse.SerializeToString,
            ),
            'EvaluateUnstructuredQuality': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateUnstructuredQuality,
                    request_deserializer=proto_dot_quality__pb2.EvaluateUnstructuredQualityRequest.FromString,
                    response_serializer=proto_dot_quality__pb2.EvaluateUnstructuredQualityResponse.SerializeToString,
            ),
            'CleanData': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanData,
                    request_deserializer=proto_dot_quality__pb2.CleanDataRequest.FromString,
                    response_serializer=proto_dot_quality__pb2.CleanDataResponse.SerializeToString,
            ),
            'ProcessPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPipeline,
                    request_deserializer=proto_dot_quality__pb2.ProcessPipelineRequest.FromString,
                    response_serializer=proto_dot_quality__pb2.ProcessPipelineResponse.SerializeToString,
            ),
            'DetectDrift': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectDrift,
                    request_deserializer=proto_dot_quality__pb2.DetectDriftRequest.FromString,
                    response_serializer=proto_dot_quality__pb2.DetectDriftResponse.SerializeToString,
            ),
            'ListDimensions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDimensions,
                    request_deserializer=proto_dot_quality__pb2.ListDimensionsRequest.FromString,
                    response_serializer=proto_dot_quality__pb2.ListDimensionsResponse.SerializeToString,
            ),
            'GetQualityRules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQualityRules,
                    request_deserializer=proto_dot_quality__pb2.GetQualityRulesRequest.FromString,
                    response_serializer=proto_dot_quality__pb2.GetQualityRulesResponse.SerializeToString,
            ),
            'UpdateQualityRules': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateQualityRules,
                    request_deserializer=proto_dot_quality__pb2.UpdateQualityRulesRequest.FromString,
                    response_serializer=proto_dot_quality__pb2.UpdateQualityRulesResponse.SerializeToString,
            ),
            'RegisterCustomEvaluator': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCustomEvaluator,
                    request_deserializer=proto_dot_quality__pb2.RegisterCustomEvaluatorRequest.FromString,
                    response_serializer=proto_dot_quality__pb2.RegisterCustomEvaluatorResponse.SerializeToString,
            ),
            'RegisterCustomCleaner': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCustomCleaner,
                    request_deserializer=proto_dot_quality__pb2.RegisterCustomCleanerRequest.FromString,
                    response_serializer=proto_dot_quality__pb2.RegisterCustomCleanerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quality.QualityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quality.QualityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QualityService(object):
    """质量服务
    """

    @staticmethod
    def EvaluateQuality(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quality.QualityService/EvaluateQuality',
            proto_dot_quality__pb2.EvaluateQualityRequest.SerializeToString,
            proto_dot_quality__pb2.EvaluateQualityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateUnstructuredQuality(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quality.QualityService/EvaluateUnstructuredQuality',
            proto_dot_quality__pb2.EvaluateUnstructuredQualityRequest.SerializeToString,
            proto_dot_quality__pb2.EvaluateUnstructuredQualityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quality.QualityService/CleanData',
            proto_dot_quality__pb2.CleanDataRequest.SerializeToString,
            proto_dot_quality__pb2.CleanDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quality.QualityService/ProcessPipeline',
            proto_dot_quality__pb2.ProcessPipelineRequest.SerializeToString,
            proto_dot_quality__pb2.ProcessPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectDrift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quality.QualityService/DetectDrift',
            proto_dot_quality__pb2.DetectDriftRequest.SerializeToString,
            proto_dot_quality__pb2.DetectDriftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDimensions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quality.QualityService/ListDimensions',
            proto_dot_quality__pb2.ListDimensionsRequest.SerializeToString,
            proto_dot_quality__pb2.ListDimensionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQualityRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quality.QualityService/GetQualityRules',
            proto_dot_quality__pb2.GetQualityRulesRequest.SerializeToString,
            proto_dot_quality__pb2.GetQualityRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateQualityRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quality.QualityService/UpdateQualityRules',
            proto_dot_quality__pb2.UpdateQualityRulesRequest.SerializeToString,
            proto_dot_quality__pb2.UpdateQualityRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterCustomEvaluator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quality.QualityService/RegisterCustomEvaluator',
            proto_dot_quality__pb2.RegisterCustomEvaluatorRequest.SerializeToString,
            proto_dot_quality__pb2.RegisterCustomEvaluatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterCustomCleaner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quality.QualityService/RegisterCustomCleaner',
            proto_dot_quality__pb2.RegisterCustomCleanerRequest.SerializeToString,
            proto_dot_quality__pb2.RegisterCustomCleanerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
