// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: api/proto/judge.proto

package judge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_UNKNOWN   TaskStatus = 0
	TaskStatus_PENDING   TaskStatus = 1 // 待处理
	TaskStatus_QUEUED    TaskStatus = 2 // 队列中
	TaskStatus_RUNNING   TaskStatus = 3 // 执行中
	TaskStatus_SCORING   TaskStatus = 4 // 评分中
	TaskStatus_COMPLETED TaskStatus = 5 // 已完成
	TaskStatus_FAILED    TaskStatus = 6 // 失败
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "QUEUED",
		3: "RUNNING",
		4: "SCORING",
		5: "COMPLETED",
		6: "FAILED",
	}
	TaskStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"PENDING":   1,
		"QUEUED":    2,
		"RUNNING":   3,
		"SCORING":   4,
		"COMPLETED": 5,
		"FAILED":    6,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_judge_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_api_proto_judge_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_judge_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_judge_proto_enumTypes[1].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_api_proto_judge_proto_enumTypes[1]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_judge_proto_rawDescGZIP(), []int{10, 0}
}

type ProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                       // 任务 ID
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=judge.TaskStatus" json:"status,omitempty"`              // 任务状态
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`                                // 进度百分比 (0-100)
	Stage         string                 `protobuf:"bytes,4,opt,name=stage,proto3" json:"stage,omitempty"`                                       // 当前阶段: queuing, inferring, scoring, completed, failed
	CurrentSample int32                  `protobuf:"varint,5,opt,name=current_sample,json=currentSample,proto3" json:"current_sample,omitempty"` // 当前样本索引
	TotalSamples  int32                  `protobuf:"varint,6,opt,name=total_samples,json=totalSamples,proto3" json:"total_samples,omitempty"`    // 总样本数
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`                                   // 状态消息
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                              // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_api_proto_judge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_judge_proto_rawDescGZIP(), []int{0}
}

func (x *ProgressUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ProgressUpdate) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_UNKNOWN
}

func (x *ProgressUpdate) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ProgressUpdate) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ProgressUpdate) GetCurrentSample() int32 {
	if x != nil {
		return x.CurrentSample
	}
	return 0
}

func (x *ProgressUpdate) GetTotalSamples() int32 {
	if x != nil {
		return x.TotalSamples
	}
	return 0
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // 是否接受
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`    // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_api_proto_judge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_judge_proto_rawDescGZIP(), []int{1}
}

func (x *ProgressResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EvaluationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                       // 任务 ID
	TotalSamples  int32                  `protobuf:"varint,2,opt,name=total_samples,json=totalSamples,proto3" json:"total_samples,omitempty"`    // 总样本数
	ScoredSamples int32                  `protobuf:"varint,3,opt,name=scored_samples,json=scoredSamples,proto3" json:"scored_samples,omitempty"` // 已评分样本数
	// 聚合指标
	AvgScore       float64 `protobuf:"fixed64,4,opt,name=avg_score,json=avgScore,proto3" json:"avg_score,omitempty"`                    // 平均分
	PassRate       float64 `protobuf:"fixed64,5,opt,name=pass_rate,json=passRate,proto3" json:"pass_rate,omitempty"`                    // 通过率
	TotalTokens    int64   `protobuf:"varint,6,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`            // 总 token 使用量
	TotalLatencyMs int64   `protobuf:"varint,7,opt,name=total_latency_ms,json=totalLatencyMs,proto3" json:"total_latency_ms,omitempty"` // 总延迟（毫秒）
	// 样本详细结果
	Samples []*SampleResult `protobuf:"bytes,8,rep,name=samples,proto3" json:"samples,omitempty"`
	// 元数据
	StartedAt     int64  `protobuf:"varint,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`          // 开始时间
	CompletedAt   int64  `protobuf:"varint,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`   // 完成时间
	ErrorMessage  string `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 错误信息（失败时）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationResult) Reset() {
	*x = EvaluationResult{}
	mi := &file_api_proto_judge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationResult) ProtoMessage() {}

func (x *EvaluationResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationResult.ProtoReflect.Descriptor instead.
func (*EvaluationResult) Descriptor() ([]byte, []int) {
	return file_api_proto_judge_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluationResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *EvaluationResult) GetTotalSamples() int32 {
	if x != nil {
		return x.TotalSamples
	}
	return 0
}

func (x *EvaluationResult) GetScoredSamples() int32 {
	if x != nil {
		return x.ScoredSamples
	}
	return 0
}

func (x *EvaluationResult) GetAvgScore() float64 {
	if x != nil {
		return x.AvgScore
	}
	return 0
}

func (x *EvaluationResult) GetPassRate() float64 {
	if x != nil {
		return x.PassRate
	}
	return 0
}

func (x *EvaluationResult) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *EvaluationResult) GetTotalLatencyMs() int64 {
	if x != nil {
		return x.TotalLatencyMs
	}
	return 0
}

func (x *EvaluationResult) GetSamples() []*SampleResult {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *EvaluationResult) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *EvaluationResult) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *EvaluationResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SampleResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SampleIndex      int32                  `protobuf:"varint,1,opt,name=sample_index,json=sampleIndex,proto3" json:"sample_index,omitempty"`                // 样本索引
	ModelOutput      string                 `protobuf:"bytes,2,opt,name=model_output,json=modelOutput,proto3" json:"model_output,omitempty"`                 // 模型输出
	Score            float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`                                              // 分数
	Passed           bool                   `protobuf:"varint,4,opt,name=passed,proto3" json:"passed,omitempty"`                                             // 是否通过
	Reason           string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                                              // 评分理由
	LatencyMs        int32                  `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`                      // 延迟（毫秒）
	PromptTokens     int64                  `protobuf:"varint,7,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`             // Prompt tokens
	CompletionTokens int64                  `protobuf:"varint,8,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"` // Completion tokens
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SampleResult) Reset() {
	*x = SampleResult{}
	mi := &file_api_proto_judge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleResult) ProtoMessage() {}

func (x *SampleResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleResult.ProtoReflect.Descriptor instead.
func (*SampleResult) Descriptor() ([]byte, []int) {
	return file_api_proto_judge_proto_rawDescGZIP(), []int{3}
}

func (x *SampleResult) GetSampleIndex() int32 {
	if x != nil {
		return x.SampleIndex
	}
	return 0
}

func (x *SampleResult) GetModelOutput() string {
	if x != nil {
		return x.ModelOutput
	}
	return ""
}

func (x *SampleResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SampleResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *SampleResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SampleResult) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *SampleResult) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *SampleResult) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

type ResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`                // 是否接受
	ResultId      string                 `protobuf:"bytes,2,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"` // 结果 ID
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                   // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_api_proto_judge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_judge_proto_rawDescGZIP(), []int{4}
}

func (x *ResultResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ResultResponse) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

func (x *ResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListDatasetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsRequest) Reset() {
	*x = ListDatasetsRequest{}
	mi := &file_api_proto_judge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsRequest) ProtoMessage() {}

func (x *ListDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsRequest.ProtoReflect.Descriptor instead.
func (*ListDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_judge_proto_rawDescGZIP(), []int{5}
}

type ListDatasetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasets      []*DatasetInfo         `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsResponse) Reset() {
	*x = ListDatasetsResponse{}
	mi := &file_api_proto_judge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsResponse) ProtoMessage() {}

func (x *ListDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsResponse.ProtoReflect.Descriptor instead.
func (*ListDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_judge_proto_rawDescGZIP(), []int{6}
}

func (x *ListDatasetsResponse) GetDatasets() []*DatasetInfo {
	if x != nil {
		return x.Datasets
	}
	return nil
}

type GetDatasetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetId     string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"` // 数据集 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatasetRequest) Reset() {
	*x = GetDatasetRequest{}
	mi := &file_api_proto_judge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatasetRequest) ProtoMessage() {}

func (x *GetDatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatasetRequest.ProtoReflect.Descriptor instead.
func (*GetDatasetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_judge_proto_rawDescGZIP(), []int{7}
}

func (x *GetDatasetRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

type DatasetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetId     string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`                                                        // 数据集 ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // 数据集名称
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                                                     // 描述
	SampleCount   int32                  `protobuf:"varint,4,opt,name=sample_count,json=sampleCount,proto3" json:"sample_count,omitempty"`                                                 // 样本数量
	Fields        []string               `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`                                                                               // 数据字段 (如: question, answer, context)
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                       // 创建时间
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                       // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetInfo) Reset() {
	*x = DatasetInfo{}
	mi := &file_api_proto_judge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetInfo) ProtoMessage() {}

func (x *DatasetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetInfo.ProtoReflect.Descriptor instead.
func (*DatasetInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_judge_proto_rawDescGZIP(), []int{8}
}

func (x *DatasetInfo) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *DatasetInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DatasetInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DatasetInfo) GetSampleCount() int32 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

func (x *DatasetInfo) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DatasetInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DatasetInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DatasetInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_judge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_judge_proto_rawDescGZIP(), []int{9}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=judge.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Version       string                            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // 服务版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_judge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_judge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_judge_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_api_proto_judge_proto protoreflect.FileDescriptor

const file_api_proto_judge_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/judge.proto\x12\x05judge\"\x8a\x02\n" +
	"\x0eProgressUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.judge.TaskStatusR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\tR\x05stage\x12%\n" +
	"\x0ecurrent_sample\x18\x05 \x01(\x05R\rcurrentSample\x12#\n" +
	"\rtotal_samples\x18\x06 \x01(\x05R\ftotalSamples\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"H\n" +
	"\x10ProgressResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x94\x03\n" +
	"\x10EvaluationResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12#\n" +
	"\rtotal_samples\x18\x02 \x01(\x05R\ftotalSamples\x12%\n" +
	"\x0escored_samples\x18\x03 \x01(\x05R\rscoredSamples\x12\x1b\n" +
	"\tavg_score\x18\x04 \x01(\x01R\bavgScore\x12\x1b\n" +
	"\tpass_rate\x18\x05 \x01(\x01R\bpassRate\x12!\n" +
	"\ftotal_tokens\x18\x06 \x01(\x03R\vtotalTokens\x12(\n" +
	"\x10total_latency_ms\x18\a \x01(\x03R\x0etotalLatencyMs\x12-\n" +
	"\asamples\x18\b \x03(\v2\x13.judge.SampleResultR\asamples\x12\x1d\n" +
	"\n" +
	"started_at\x18\t \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\x03R\vcompletedAt\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\"\x8b\x02\n" +
	"\fSampleResult\x12!\n" +
	"\fsample_index\x18\x01 \x01(\x05R\vsampleIndex\x12!\n" +
	"\fmodel_output\x18\x02 \x01(\tR\vmodelOutput\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x16\n" +
	"\x06passed\x18\x04 \x01(\bR\x06passed\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x05R\tlatencyMs\x12#\n" +
	"\rprompt_tokens\x18\a \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\b \x01(\x03R\x10completionTokens\"c\n" +
	"\x0eResultResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1b\n" +
	"\tresult_id\x18\x02 \x01(\tR\bresultId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x15\n" +
	"\x13ListDatasetsRequest\"F\n" +
	"\x14ListDatasetsResponse\x12.\n" +
	"\bdatasets\x18\x01 \x03(\v2\x12.judge.DatasetInfoR\bdatasets\"2\n" +
	"\x11GetDatasetRequest\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\"\xd6\x02\n" +
	"\vDatasetInfo\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fsample_count\x18\x04 \x01(\x05R\vsampleCount\x12\x16\n" +
	"\x06fields\x18\x05 \x03(\tR\x06fields\x12<\n" +
	"\bmetadata\x18\x06 \x03(\v2 .judge.DatasetInfo.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12HealthCheckRequest\"\xad\x01\n" +
	"\x13HealthCheckResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.judge.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02*g\n" +
	"\n" +
	"TaskStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x02\x12\v\n" +
	"\aRUNNING\x10\x03\x12\v\n" +
	"\aSCORING\x10\x04\x12\r\n" +
	"\tCOMPLETED\x10\x05\x12\n" +
	"\n" +
	"\x06FAILED\x10\x062\xdd\x02\n" +
	"\fJudgeService\x12B\n" +
	"\x0eReportProgress\x12\x15.judge.ProgressUpdate\x1a\x17.judge.ProgressResponse(\x01\x12>\n" +
	"\fSubmitResult\x12\x17.judge.EvaluationResult\x1a\x15.judge.ResultResponse\x12G\n" +
	"\fListDatasets\x12\x1a.judge.ListDatasetsRequest\x1a\x1b.judge.ListDatasetsResponse\x12:\n" +
	"\n" +
	"GetDataset\x12\x18.judge.GetDatasetRequest\x1a\x12.judge.DatasetInfo\x12D\n" +
	"\vHealthCheck\x12\x19.judge.HealthCheckRequest\x1a\x1a.judge.HealthCheckResponseB\x16Z\x14link/api/proto/judgeb\x06proto3"

var (
	file_api_proto_judge_proto_rawDescOnce sync.Once
	file_api_proto_judge_proto_rawDescData []byte
)

func file_api_proto_judge_proto_rawDescGZIP() []byte {
	file_api_proto_judge_proto_rawDescOnce.Do(func() {
		file_api_proto_judge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_judge_proto_rawDesc), len(file_api_proto_judge_proto_rawDesc)))
	})
	return file_api_proto_judge_proto_rawDescData
}

var file_api_proto_judge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_judge_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_judge_proto_goTypes = []any{
	(TaskStatus)(0),                        // 0: judge.TaskStatus
	(HealthCheckResponse_ServingStatus)(0), // 1: judge.HealthCheckResponse.ServingStatus
	(*ProgressUpdate)(nil),                 // 2: judge.ProgressUpdate
	(*ProgressResponse)(nil),               // 3: judge.ProgressResponse
	(*EvaluationResult)(nil),               // 4: judge.EvaluationResult
	(*SampleResult)(nil),                   // 5: judge.SampleResult
	(*ResultResponse)(nil),                 // 6: judge.ResultResponse
	(*ListDatasetsRequest)(nil),            // 7: judge.ListDatasetsRequest
	(*ListDatasetsResponse)(nil),           // 8: judge.ListDatasetsResponse
	(*GetDatasetRequest)(nil),              // 9: judge.GetDatasetRequest
	(*DatasetInfo)(nil),                    // 10: judge.DatasetInfo
	(*HealthCheckRequest)(nil),             // 11: judge.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 12: judge.HealthCheckResponse
	nil,                                    // 13: judge.DatasetInfo.MetadataEntry
}
var file_api_proto_judge_proto_depIdxs = []int32{
	0,  // 0: judge.ProgressUpdate.status:type_name -> judge.TaskStatus
	5,  // 1: judge.EvaluationResult.samples:type_name -> judge.SampleResult
	10, // 2: judge.ListDatasetsResponse.datasets:type_name -> judge.DatasetInfo
	13, // 3: judge.DatasetInfo.metadata:type_name -> judge.DatasetInfo.MetadataEntry
	1,  // 4: judge.HealthCheckResponse.status:type_name -> judge.HealthCheckResponse.ServingStatus
	2,  // 5: judge.JudgeService.ReportProgress:input_type -> judge.ProgressUpdate
	4,  // 6: judge.JudgeService.SubmitResult:input_type -> judge.EvaluationResult
	7,  // 7: judge.JudgeService.ListDatasets:input_type -> judge.ListDatasetsRequest
	9,  // 8: judge.JudgeService.GetDataset:input_type -> judge.GetDatasetRequest
	11, // 9: judge.JudgeService.HealthCheck:input_type -> judge.HealthCheckRequest
	3,  // 10: judge.JudgeService.ReportProgress:output_type -> judge.ProgressResponse
	6,  // 11: judge.JudgeService.SubmitResult:output_type -> judge.ResultResponse
	8,  // 12: judge.JudgeService.ListDatasets:output_type -> judge.ListDatasetsResponse
	10, // 13: judge.JudgeService.GetDataset:output_type -> judge.DatasetInfo
	12, // 14: judge.JudgeService.HealthCheck:output_type -> judge.HealthCheckResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_judge_proto_init() }
func file_api_proto_judge_proto_init() {
	if File_api_proto_judge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_judge_proto_rawDesc), len(file_api_proto_judge_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_judge_proto_goTypes,
		DependencyIndexes: file_api_proto_judge_proto_depIdxs,
		EnumInfos:         file_api_proto_judge_proto_enumTypes,
		MessageInfos:      file_api_proto_judge_proto_msgTypes,
	}.Build()
	File_api_proto_judge_proto = out.File
	file_api_proto_judge_proto_goTypes = nil
	file_api_proto_judge_proto_depIdxs = nil
}
