// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: api/proto/judge.proto

package judge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JudgeService_ReportProgress_FullMethodName = "/judge.JudgeService/ReportProgress"
	JudgeService_SubmitResult_FullMethodName   = "/judge.JudgeService/SubmitResult"
	JudgeService_ListDatasets_FullMethodName   = "/judge.JudgeService/ListDatasets"
	JudgeService_GetDataset_FullMethodName     = "/judge.JudgeService/GetDataset"
	JudgeService_HealthCheck_FullMethodName    = "/judge.JudgeService/HealthCheck"
)

// JudgeServiceClient is the client API for JudgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LLM 评测服务
type JudgeServiceClient interface {
	// 上报评测进度（单向流）
	ReportProgress(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ProgressUpdate, ProgressResponse], error)
	// 提交评测结果
	SubmitResult(ctx context.Context, in *EvaluationResult, opts ...grpc.CallOption) (*ResultResponse, error)
	// 获取可用数据集列表
	ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error)
	// 获取数据集详情
	GetDataset(ctx context.Context, in *GetDatasetRequest, opts ...grpc.CallOption) (*DatasetInfo, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type judgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJudgeServiceClient(cc grpc.ClientConnInterface) JudgeServiceClient {
	return &judgeServiceClient{cc}
}

func (c *judgeServiceClient) ReportProgress(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ProgressUpdate, ProgressResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JudgeService_ServiceDesc.Streams[0], JudgeService_ReportProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProgressUpdate, ProgressResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JudgeService_ReportProgressClient = grpc.ClientStreamingClient[ProgressUpdate, ProgressResponse]

func (c *judgeServiceClient) SubmitResult(ctx context.Context, in *EvaluationResult, opts ...grpc.CallOption) (*ResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, JudgeService_SubmitResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeServiceClient) ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatasetsResponse)
	err := c.cc.Invoke(ctx, JudgeService_ListDatasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeServiceClient) GetDataset(ctx context.Context, in *GetDatasetRequest, opts ...grpc.CallOption) (*DatasetInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatasetInfo)
	err := c.cc.Invoke(ctx, JudgeService_GetDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, JudgeService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JudgeServiceServer is the server API for JudgeService service.
// All implementations must embed UnimplementedJudgeServiceServer
// for forward compatibility.
//
// LLM 评测服务
type JudgeServiceServer interface {
	// 上报评测进度（单向流）
	ReportProgress(grpc.ClientStreamingServer[ProgressUpdate, ProgressResponse]) error
	// 提交评测结果
	SubmitResult(context.Context, *EvaluationResult) (*ResultResponse, error)
	// 获取可用数据集列表
	ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error)
	// 获取数据集详情
	GetDataset(context.Context, *GetDatasetRequest) (*DatasetInfo, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedJudgeServiceServer()
}

// UnimplementedJudgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJudgeServiceServer struct{}

func (UnimplementedJudgeServiceServer) ReportProgress(grpc.ClientStreamingServer[ProgressUpdate, ProgressResponse]) error {
	return status.Error(codes.Unimplemented, "method ReportProgress not implemented")
}
func (UnimplementedJudgeServiceServer) SubmitResult(context.Context, *EvaluationResult) (*ResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResult not implemented")
}
func (UnimplementedJudgeServiceServer) ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatasets not implemented")
}
func (UnimplementedJudgeServiceServer) GetDataset(context.Context, *GetDatasetRequest) (*DatasetInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDataset not implemented")
}
func (UnimplementedJudgeServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedJudgeServiceServer) mustEmbedUnimplementedJudgeServiceServer() {}
func (UnimplementedJudgeServiceServer) testEmbeddedByValue()                      {}

// UnsafeJudgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JudgeServiceServer will
// result in compilation errors.
type UnsafeJudgeServiceServer interface {
	mustEmbedUnimplementedJudgeServiceServer()
}

func RegisterJudgeServiceServer(s grpc.ServiceRegistrar, srv JudgeServiceServer) {
	// If the following call panics, it indicates UnimplementedJudgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JudgeService_ServiceDesc, srv)
}

func _JudgeService_ReportProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JudgeServiceServer).ReportProgress(&grpc.GenericServerStream[ProgressUpdate, ProgressResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JudgeService_ReportProgressServer = grpc.ClientStreamingServer[ProgressUpdate, ProgressResponse]

func _JudgeService_SubmitResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluationResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).SubmitResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeService_SubmitResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).SubmitResult(ctx, req.(*EvaluationResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _JudgeService_ListDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).ListDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeService_ListDatasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).ListDatasets(ctx, req.(*ListDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JudgeService_GetDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).GetDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeService_GetDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).GetDataset(ctx, req.(*GetDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JudgeService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JudgeService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JudgeService_ServiceDesc is the grpc.ServiceDesc for JudgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JudgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "judge.JudgeService",
	HandlerType: (*JudgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitResult",
			Handler:    _JudgeService_SubmitResult_Handler,
		},
		{
			MethodName: "ListDatasets",
			Handler:    _JudgeService_ListDatasets_Handler,
		},
		{
			MethodName: "GetDataset",
			Handler:    _JudgeService_GetDataset_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _JudgeService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportProgress",
			Handler:       _JudgeService_ReportProgress_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/judge.proto",
}
